"""Local HA verification script tests."""

from __future__ import annotations

from pathlib import Path

from scripts.verify_local_ha import (
    REQUIRED_RUNTIME_MODULES,
    SOURCE_COMPONENT_ROOT,
    VerificationReport,
    forbidden_install_paths,
    parse_domain_counts,
    runtime_diff,
    verify_required_modules,
)


def test_runtime_diff_ignores_ha_generated_cache(tmp_path: Path) -> None:
    """Runtime comparison should ignore pycache generated by HA."""
    source = tmp_path / "source"
    installed = tmp_path / "installed"
    source.mkdir()
    installed.mkdir()
    (source / "__init__.py").write_text("ok = True\n", encoding="utf-8")
    (installed / "__init__.py").write_text("ok = True\n", encoding="utf-8")
    cache = installed / "__pycache__"
    cache.mkdir()
    (cache / "__init__.cpython-314.pyc").write_bytes(b"cache")

    diff = runtime_diff(source, installed)

    assert diff.ok


def test_runtime_diff_detects_changed_runtime_file(tmp_path: Path) -> None:
    """Runtime comparison should detect installed source drift."""
    source = tmp_path / "source"
    installed = tmp_path / "installed"
    source.mkdir()
    installed.mkdir()
    (source / "manifest.json").write_text('{"version": "1"}', encoding="utf-8")
    (installed / "manifest.json").write_text('{"version": "2"}', encoding="utf-8")

    diff = runtime_diff(source, installed)

    assert diff.changed == ("manifest.json",)


def test_required_modules_fail_for_missing_support_module(tmp_path: Path) -> None:
    """本地 HA 验证应发现缺失的关键支持模块."""
    install_root = tmp_path / "config" / "custom_components" / "yeelight_pro"
    install_root.mkdir(parents=True)
    report = VerificationReport()

    verify_required_modules(
        install_root,
        report,
        modules=("custom_components.yeelight_pro.missing_support",),
    )

    assert not report.ok
    assert any("missing_support" in failure for failure in report.failures)


def test_required_modules_include_device_trigger_contract() -> None:
    """本地 HA 安装态必须保留自动化 device trigger 模块."""
    assert (
        "custom_components.yeelight_pro.device_trigger"
        in REQUIRED_RUNTIME_MODULES
    )


def test_required_modules_include_ha_device_registry_contract() -> None:
    """本地 HA 安装态必须保留 HA device registry 同步模块."""
    assert (
        "custom_components.yeelight_pro.ha_device_registry"
        in REQUIRED_RUNTIME_MODULES
    )


def test_required_modules_include_client_node_api_contract() -> None:
    """本地 HA 安装态必须保留拆分后的 Open API 节点模块."""
    expected_modules = {
        "custom_components.yeelight_pro.core.client_node_api",
        "custom_components.yeelight_pro.core.client_node_base",
        "custom_components.yeelight_pro.core.client_node_lists",
        "custom_components.yeelight_pro.core.client_node_properties",
    }
    assert expected_modules <= set(REQUIRED_RUNTIME_MODULES)

def test_required_modules_include_spec_correction_normalizers() -> None:
    """本地 HA 安装态必须保留拆分后的 spec correction normalizer."""
    assert (
        "custom_components.yeelight_pro.capabilities.spec_correction_normalizers"
        in REQUIRED_RUNTIME_MODULES
    )


def test_required_modules_include_platform_contract_data() -> None:
    """本地 HA 安装态必须保留拆分后的平台合同数据模块."""
    assert (
        "custom_components.yeelight_pro.capabilities.platform_contract_data"
        in REQUIRED_RUNTIME_MODULES
    )


def test_required_modules_include_platform_contract_evidence() -> None:
    """本地 HA 安装态必须保留平台候选能力证据 helper."""
    assert (
        "custom_components.yeelight_pro.capabilities.platform_contract_evidence"
        in REQUIRED_RUNTIME_MODULES
    )


def test_required_modules_include_property_index_helper() -> None:
    """本地 HA 安装态必须保留官方组件属性反向索引 helper."""
    assert (
        "custom_components.yeelight_pro.capabilities.property_index"
        in REQUIRED_RUNTIME_MODULES
    )


def test_required_modules_include_property_hydration_summary() -> None:
    """本地 HA 安装态必须保留补水聚合诊断 helper."""
    assert (
        "custom_components.yeelight_pro.core.property_hydration_summary"
        in REQUIRED_RUNTIME_MODULES
    )


def test_required_modules_include_runtime_inference_helper() -> None:
    """本地 HA 安装态必须保留运行时推断 helper."""
    assert (
        "custom_components.yeelight_pro.converter.runtime_inference_helpers"
        in REQUIRED_RUNTIME_MODULES
    )


def test_required_modules_include_product_catalog_helpers() -> None:
    """本地 HA 安装态必须保留易来产品构成目录."""
    assert {
        "custom_components.yeelight_pro.capabilities.product_catalog",
        "custom_components.yeelight_pro.capabilities.product_catalog_data",
    } <= set(REQUIRED_RUNTIME_MODULES)


def test_required_modules_include_openapi_property_helper() -> None:
    """本地 HA 安装态必须保留 OpenAPI 属性元数据转换 helper."""
    assert (
        "custom_components.yeelight_pro.converter.openapi_properties"
        in REQUIRED_RUNTIME_MODULES
    )


def test_required_modules_include_device_classification_categories() -> None:
    """本地 HA 安装态必须保留设备分类别名词表."""
    assert (
        "custom_components.yeelight_pro.core.device_classification_categories"
        in REQUIRED_RUNTIME_MODULES
    )


def test_required_modules_include_device_runtime_capabilities() -> None:
    """本地 HA 安装态必须保留运行时能力分类 helper."""
    assert (
        "custom_components.yeelight_pro.core.device_runtime_capabilities"
        in REQUIRED_RUNTIME_MODULES
    )
    assert (
        "custom_components.yeelight_pro.core.device_registry_classification"
        in REQUIRED_RUNTIME_MODULES
    )
    assert (
        "custom_components.yeelight_pro.core.device_runtime_constants"
        in REQUIRED_RUNTIME_MODULES
    )
    assert (
        "custom_components.yeelight_pro.core.lan_topology_payload"
        in REQUIRED_RUNTIME_MODULES
    )
    assert (
        "custom_components.yeelight_pro.core.firmware_metadata"
        in REQUIRED_RUNTIME_MODULES
    )


def test_required_modules_include_runtime_template_helpers() -> None:
    """本地 HA 安装态必须保留运行时模板拆分模块."""
    expected_modules = {
        "custom_components.yeelight_pro.converter.runtime_template_constants",
        "custom_components.yeelight_pro.converter.runtime_template_controls",
        "custom_components.yeelight_pro.converter.runtime_template_hvac",
        "custom_components.yeelight_pro.converter.runtime_template_selector",
        "custom_components.yeelight_pro.converter.runtime_template_sensors",
        "custom_components.yeelight_pro.converter.runtime_templates",
    }
    assert expected_modules <= set(REQUIRED_RUNTIME_MODULES)


def test_required_modules_include_config_flow_options_helper() -> None:
    """本地 HA 安装态必须保留拆分后的 options flow helper."""
    assert (
        "custom_components.yeelight_pro.config_flow_options"
        in REQUIRED_RUNTIME_MODULES
    )


def test_required_modules_include_config_flow_account_helper() -> None:
    """本地 HA 安装态必须保留扫码登录账号隔离 helper."""
    assert (
        "custom_components.yeelight_pro.config_flow_account"
        in REQUIRED_RUNTIME_MODULES
    )


def test_required_modules_include_event_projector_helper() -> None:
    """本地 HA 安装态必须保留拆分后的 event projector helper."""
    assert (
        "custom_components.yeelight_pro.projector.event_identity_helpers"
        in REQUIRED_RUNTIME_MODULES
    )
    assert (
        "custom_components.yeelight_pro.projector.event_input"
        in REQUIRED_RUNTIME_MODULES
    )
    assert (
        "custom_components.yeelight_pro.projector.event_helpers"
        in REQUIRED_RUNTIME_MODULES
    )


def test_required_modules_include_sensor_projector_helper() -> None:
    """本地 HA 安装态必须保留拆分后的 sensor projector helper."""
    assert (
        "custom_components.yeelight_pro.projector.sensor_helpers"
        in REQUIRED_RUNTIME_MODULES
    )
    assert (
        "custom_components.yeelight_pro.projector.sensor_metadata"
        in REQUIRED_RUNTIME_MODULES
    )


def test_required_modules_include_entity_category_helper() -> None:
    """本地 HA 安装态必须保留实体分类 helper。"""
    assert (
        "custom_components.yeelight_pro.entity_category"
        in REQUIRED_RUNTIME_MODULES
    )


def test_required_modules_include_entity_id_migration_helper() -> None:
    """本地 HA 安装态必须保留安全 entity_id 迁移 helper."""
    assert (
        "custom_components.yeelight_pro.entity_lifecycle_entity_id"
        in REQUIRED_RUNTIME_MODULES
    )


def test_required_modules_include_device_select_helper() -> None:
    """本地 HA 安装态必须保留设备级 select helper。"""
    assert (
        "custom_components.yeelight_pro.device_select"
        in REQUIRED_RUNTIME_MODULES
    )


def test_required_modules_include_protocol_contract_modules() -> None:
    """本地 HA 安装态必须保留 no-network 协议合同模块."""
    expected_modules = {
        "custom_components.yeelight_pro.scan_login_contract",
        "custom_components.yeelight_pro.core.scan_login",
        "custom_components.yeelight_pro.push_contract",
        "custom_components.yeelight_pro.push_manager",
        "custom_components.yeelight_pro.push_transport",
        "custom_components.yeelight_pro.core.runtime_bridge",
        "custom_components.yeelight_pro.lan_contract",
        "custom_components.yeelight_pro.lan_methods",
        "custom_components.yeelight_pro.lan_payload",
        "custom_components.yeelight_pro.lan_runtime",
        "custom_components.yeelight_pro.live_runtime",
        "custom_components.yeelight_pro.core.coordinator_controls",
        "custom_components.yeelight_pro.core.lan_control",
    }

    assert expected_modules <= set(REQUIRED_RUNTIME_MODULES)


def test_forbidden_install_paths_rejects_tests_and_text(tmp_path: Path) -> None:
    """Installed HA target must not retain release-excluded files."""
    install = tmp_path / "yeelight_pro"
    tests_dir = install / "tests"
    tests_dir.mkdir(parents=True)
    (tests_dir / "test_old.py").write_text("", encoding="utf-8")
    (install / "text.py").write_text("", encoding="utf-8")

    assert forbidden_install_paths(install) == ["tests", "tests/test_old.py", "text.py"]


def test_parse_domain_counts() -> None:
    """Expected entity-domain counts should be CLI-overridable."""
    assert parse_domain_counts("light=2,switch=1") == {"light": 2, "switch": 1}


def test_source_component_root_exists() -> None:
    """The verification script should point at the packaged source component."""
    assert SOURCE_COMPONENT_ROOT.exists()
