"""Constants for local HA verification."""

from __future__ import annotations

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[2]
SOURCE_COMPONENT_ROOT = ROOT / "custom_components" / "yeelight_pro"
DOMAIN = "yeelight_pro"

DEFAULT_CONTAINER = "yeelight-pro-ha-verify"
DEFAULT_HA_URL = "http://localhost:18124"
DEFAULT_ENTITY_COUNTS = {
    "button": 21,
    "binary_sensor": 1,
    "light": 77,
    "number": 15,
    "select": 8,
    "sensor": 48,
    "switch": 87,
}
DEFAULT_EXPECTED_ENTITIES = sum(DEFAULT_ENTITY_COUNTS.values())
DEFAULT_EXPECTED_DEVICES = 75
DEFAULT_EXPECTED_CONFIG_ENTRIES = 1

EXCLUDED_COMPARE_PARTS = {
    "__pycache__",
    ".pytest_cache",
    ".ruff_cache",
    ".mypy_cache",
    "tests",
}
EXCLUDED_COMPARE_SUFFIXES = {".pyc", ".pyo"}
FORBIDDEN_INSTALL_PARTS = {
    ".pytest_cache",
    ".ruff_cache",
    ".mypy_cache",
    "htmlcov",
    "tests",
}
FORBIDDEN_INSTALL_NAMES = {
    ".coverage",
    "coverage.json",
    "coverage.xml",
    "text.py",
    "yeelight_pro.zip",
}
REQUIRED_SERVICES = {
    "assign_areas",
    "auto_assign_areas",
    "cleanup_registry",
    "debug_emit_event",
    "refresh",
}
REQUIRED_RUNTIME_MODULES = (
    "custom_components.yeelight_pro.refresh_service",
    "custom_components.yeelight_pro.registry_cleanup_service",
    "custom_components.yeelight_pro.lan_contract",
    "custom_components.yeelight_pro.lan_discovery",
    "custom_components.yeelight_pro.lan_methods",
    "custom_components.yeelight_pro.lan_payload",
    "custom_components.yeelight_pro.lan_runtime",
    "custom_components.yeelight_pro.live_runtime",
    "custom_components.yeelight_pro.light_control_helpers",
    "custom_components.yeelight_pro.light_group",
    "custom_components.yeelight_pro.node_light",
    "custom_components.yeelight_pro.node_metadata",
    "custom_components.yeelight_pro.analytics_sensor",
    "custom_components.yeelight_pro.scan_login_contract",
    "custom_components.yeelight_pro.projector.climate_helpers",
    "custom_components.yeelight_pro.projector.event_identity_helpers",
    "custom_components.yeelight_pro.projector.event_input",
    "custom_components.yeelight_pro.projector.event_helpers",
    "custom_components.yeelight_pro.projector.property_control_common",
    "custom_components.yeelight_pro.projector.property_control_ownership",
    "custom_components.yeelight_pro.projector.sensor_helpers",
    "custom_components.yeelight_pro.projector.sensor_metadata",
    "custom_components.yeelight_pro.push_contract",
    "custom_components.yeelight_pro.push_manager",
    "custom_components.yeelight_pro.push_transport",
    "custom_components.yeelight_pro.push_transport_frames",
    "custom_components.yeelight_pro.push_transport_types",
    "custom_components.yeelight_pro.capabilities.spec_correction_normalizers",
    "custom_components.yeelight_pro.capabilities.platform_candidate_projection",
    "custom_components.yeelight_pro.capabilities.platform_contract",
    "custom_components.yeelight_pro.capabilities.platform_contract_data",
    "custom_components.yeelight_pro.capabilities.platform_contract_evidence",
    "custom_components.yeelight_pro.capabilities.platform_contract_logging",
    "custom_components.yeelight_pro.capabilities.property_index",
    "custom_components.yeelight_pro.capabilities.product_catalog",
    "custom_components.yeelight_pro.capabilities.product_catalog_data",
    "custom_components.yeelight_pro.capabilities.product_catalog_model",
    "custom_components.yeelight_pro.capabilities.ha_platforms",
    "custom_components.yeelight_pro.converter.openapi_properties",
    "custom_components.yeelight_pro.converter.runtime_inference_helpers",
    "custom_components.yeelight_pro.converter.runtime_property_builder",
    "custom_components.yeelight_pro.converter.runtime_registry_events",
    "custom_components.yeelight_pro.converter.runtime_template_constants",
    "custom_components.yeelight_pro.converter.runtime_template_controls",
    "custom_components.yeelight_pro.converter.runtime_template_hvac",
    "custom_components.yeelight_pro.converter.runtime_template_selector",
    "custom_components.yeelight_pro.converter.runtime_template_sensors",
    "custom_components.yeelight_pro.converter.runtime_templates",
    "custom_components.yeelight_pro.converter.runtime_subdevices",
    "custom_components.yeelight_pro.config_flow_account",
    "custom_components.yeelight_pro.config_flow_device_picker",
    "custom_components.yeelight_pro.config_flow_lan",
    "custom_components.yeelight_pro.entry_setup",
    "custom_components.yeelight_pro.entry_title",
    "custom_components.yeelight_pro.config_flow_options",
    "custom_components.yeelight_pro.config_flow_precheck",
    "custom_components.yeelight_pro.config_flow_reauth",
    "custom_components.yeelight_pro.config_flow_scan_login",
    "custom_components.yeelight_pro.config_flow_scan_login_helpers",
    "custom_components.yeelight_pro.config_flow_scan_login_region",
    "custom_components.yeelight_pro.device_channel_semantics",
    "custom_components.yeelight_pro.device_channel_catalog",
    "custom_components.yeelight_pro.device_channels",
    "custom_components.yeelight_pro.device_display",
    "custom_components.yeelight_pro.device_select",
    "custom_components.yeelight_pro.entity_device_id",
    "custom_components.yeelight_pro.core.schema_cache",
    "custom_components.yeelight_pro.core.client",
    "custom_components.yeelight_pro.core.analytics_coordinator",
    "custom_components.yeelight_pro.core.client_data_analytics",
    "custom_components.yeelight_pro.core.client_node_base",
    "custom_components.yeelight_pro.core.client_node_api",
    "custom_components.yeelight_pro.core.client_node_lists",
    "custom_components.yeelight_pro.core.client_node_properties",
    "custom_components.yeelight_pro.core.client_request",
    "custom_components.yeelight_pro.core.coordinator_controls",
    "custom_components.yeelight_pro.core.device_classification_categories",
    "custom_components.yeelight_pro.core.device_registry_classification",
    "custom_components.yeelight_pro.core.device_runtime_capabilities",
    "custom_components.yeelight_pro.core.device_runtime_constants",
    "custom_components.yeelight_pro.core.device_metadata",
    "custom_components.yeelight_pro.core.firmware_metadata",
    "custom_components.yeelight_pro.core.lan_control",
    "custom_components.yeelight_pro.core.lan_sensor_values",
    "custom_components.yeelight_pro.core.lan_topology_merge",
    "custom_components.yeelight_pro.core.lan_topology_payload",
    "custom_components.yeelight_pro.core.property_hydration",
    "custom_components.yeelight_pro.core.property_hydration_summary",
    "custom_components.yeelight_pro.core.coordinator_runtime",
    "custom_components.yeelight_pro.core.scan_login",
    "custom_components.yeelight_pro.core.runtime_bridge",
    "custom_components.yeelight_pro.diagnostics",
    "custom_components.yeelight_pro.diagnostic_inventory",
    "custom_components.yeelight_pro.diagnostic_options",
    "custom_components.yeelight_pro.diagnostic_payloads",
    "custom_components.yeelight_pro.diagnostic_runtime",
    "custom_components.yeelight_pro.entity_candidate_logging",
    "custom_components.yeelight_pro.entity_category",
    "custom_components.yeelight_pro.event_identity",
    "custom_components.yeelight_pro.device_trigger",
    "custom_components.yeelight_pro.entity_lifecycle_cleanup",
    "custom_components.yeelight_pro.entity_lifecycle_entity_id",
    "custom_components.yeelight_pro.entity_lifecycle_superseded",
    "custom_components.yeelight_pro.ha_device_registry",
    "custom_components.yeelight_pro.ha_house_registry",
    "custom_components.yeelight_pro.repair_issues",
    "custom_components.yeelight_pro.debug_service",
    "custom_components.yeelight_pro.deployment_urls",
    "custom_components.yeelight_pro.registry_cleanup_service",
)
SENSITIVE_CACHE_MARKERS = {
    "access_token",
    "accesstoken",
    "authorization",
    "device_id",
    "deviceid",
    "deviceids",
    "devices",
    "house_id",
    "houseid",
    "houseids",
    "houses",
    "localtoken",
    "mac",
    "mac_address",
    "macaddress",
    "password",
    "private_domain",
    "private_push_domain",
    "private_push_proxy",
    "privatedomain",
    "privatepushdomain",
    "privatepushproxy",
    "raw_payload",
    "rawpayload",
    "room_id",
    "roomid",
    "roomids",
    "roomname",
    "rooms",
    "token",
    "username",
}
SENSITIVE_CACHE_VALUE_PATTERNS = (
    re.compile(r"\bbearer\s+[a-z0-9._~+/=-]+", re.IGNORECASE),
    re.compile(r"\b(?:access_)?token\s*[:=]", re.IGNORECASE),
    re.compile(r"\bauthorization\s*[:=]", re.IGNORECASE),
    re.compile(r"\bhouse(?:_?id)?\s*[:=]", re.IGNORECASE),
    re.compile(r"\bdevice(?:_?id)?\s*[:=]", re.IGNORECASE),
    re.compile(r"\broom(?:_?id)?\s*[:=]", re.IGNORECASE),
    re.compile(r"\bmac(?:_address)?\s*[:=]", re.IGNORECASE),
)
BAD_LOG_MARKERS = {
    "ERROR",
    "ImportError",
    "ModuleNotFoundError",
    "Traceback",
}
YEELIGHT_LOG_MARKERS = {
    "custom_components.yeelight_pro",
    "custom_components/yeelight_pro",
    "yeelight_pro",
}
