"""运行时温控与安全类属性模板。"""

from __future__ import annotations

from typing import Any, Final

RUNTIME_HVAC_TEMPLATES: Final[dict[str, dict[str, dict[str, Any]]]] = {
    "fresh_air": {
        "vmcp": {
            "name": "新风开关",
            "kind": "control",
            "property_type": "apply",
            "format": "boolean",
            "access": "read_write",
        },
        "vmcf": {
            "name": "新风风速",
            "kind": "control",
            "property_type": "apply",
            "format": "uint8",
            "access": "read_write",
            "value_range": (1, 100, 1),
        },
    },
    "climate": {
        "acm": {
            "name": "模式",
            "kind": "control",
            "property_type": "apply",
            "format": "uint8",
            "access": "read_write",
        },
        "actt": {
            "name": "目标温度",
            "kind": "control",
            "property_type": "apply",
            "format": "float",
            "unit": "°C",
            "access": "read_write",
        },
        "acct": {
            "name": "当前温度",
            "kind": "state",
            "property_type": "apply",
            "format": "float",
            "unit": "°C",
            "access": "read_only",
        },
        "acf": {
            "name": "风速",
            "kind": "control",
            "property_type": "apply",
            "format": "uint8",
            "access": "read_write",
        },
        "aco": {
            "name": "在线",
            "kind": "state",
            "property_type": "apply",
            "format": "boolean",
            "access": "read_only",
        },
    },
    "temp_control": {
        "p": {
            "name": "开关",
            "kind": "control",
            "property_type": "apply",
            "format": "boolean",
            "access": "read_write",
        },
        "acp": {
            "name": "空调开关",
            "kind": "control",
            "property_type": "apply",
            "format": "boolean",
            "access": "read_write",
        },
        "aco": {
            "name": "在线",
            "kind": "state",
            "property_type": "apply",
            "format": "boolean",
            "access": "read_only",
        },
        "acm": {
            "name": "模式",
            "kind": "control",
            "property_type": "apply",
            "format": "uint8",
            "access": "read_write",
        },
        "actt": {
            "name": "目标温度",
            "kind": "control",
            "property_type": "apply",
            "format": "float",
            "unit": "°C",
            "access": "read_write",
        },
        "acct": {
            "name": "当前温度",
            "kind": "state",
            "property_type": "apply",
            "format": "float",
            "unit": "°C",
            "access": "read_only",
        },
        "acf": {
            "name": "风速",
            "kind": "control",
            "property_type": "apply",
            "format": "uint8",
            "access": "read_write",
        },
        "t": {
            "name": "温度",
            "kind": "state",
            "property_type": "apply",
            "format": "float",
            "unit": "°C",
            "access": "read_only",
        },
        "h": {
            "name": "湿度",
            "kind": "state",
            "property_type": "apply",
            "format": "float",
            "unit": "%",
            "access": "read_only",
        },
        "tgt": {
            "name": "目标温度",
            "kind": "control",
            "property_type": "apply",
            "format": "float",
            "unit": "°C",
            "access": "read_write",
            "value_range": (0, 50, 1),
        },
        "rfhp": {
            "name": "地暖开关",
            "kind": "control",
            "property_type": "apply",
            "format": "boolean",
            "access": "read_write",
        },
        "rfhct": {
            "name": "地暖当前温度",
            "kind": "state",
            "property_type": "apply",
            "format": "float",
            "unit": "°C",
            "access": "read_only",
        },
        "rfhtt": {
            "name": "地暖目标温度",
            "kind": "control",
            "property_type": "apply",
            "format": "float",
            "unit": "°C",
            "access": "read_write",
        },
        "bhm": {
            "name": "浴霸模式",
            "kind": "control",
            "property_type": "apply",
            "format": "uint8",
            "access": "read_write",
        },
        "do": {
            "name": "延时关闭",
            "kind": "control",
            "property_type": "apply",
            "format": "uint16",
            "unit": "min",
            "access": "read_write",
            "value_range": (1, 120, 1),
        },
        "ve": {
            "name": "换气档位",
            "kind": "control",
            "property_type": "apply",
            "format": "uint8",
            "access": "read_write",
        },
        "fa": {
            "name": "风扇档位",
            "kind": "control",
            "property_type": "apply",
            "format": "uint8",
            "access": "read_write",
        },
        "he": {
            "name": "加热档位",
            "kind": "control",
            "property_type": "apply",
            "format": "uint8",
            "access": "read_write",
        },
        "sa": {
            "name": "摆动角度",
            "kind": "config",
            "property_type": "config",
            "format": "uint8",
            "access": "read_write",
            "value_range": (60, 120, 1),
        },
        "ss": {
            "name": "摆动模式",
            "kind": "config",
            "property_type": "config",
            "format": "uint8",
            "access": "read_write",
        },
        "rst": {
            "name": "房间面积",
            "kind": "config",
            "property_type": "config",
            "format": "uint8",
            "access": "read_write",
        },
    },
}
