"""运行时传感类属性模板。"""

from __future__ import annotations

from typing import Any, Final

RUNTIME_SENSOR_TEMPLATES: Final[dict[str, dict[str, dict[str, Any]]]] = {
    "binary_sensor": {
        "mv": {
            "name": "人体移动",
            "kind": "state",
            "property_type": "apply",
            "format": "boolean",
            "access": "read_only",
        },
        "dc": {
            "name": "门窗状态",
            "kind": "state",
            "property_type": "apply",
            "format": "boolean",
            "access": "read_only",
        },
        "alm": {
            "name": "防拆",
            "kind": "state",
            "property_type": "apply",
            "format": "boolean",
            "access": "read_only",
        },
    },
    "contact_sensor": {
        "dc": {
            "name": "门窗状态",
            "kind": "state",
            "property_type": "apply",
            "format": "boolean",
            "access": "read_only",
        },
        "alm": {
            "name": "防拆",
            "kind": "state",
            "property_type": "apply",
            "format": "boolean",
            "access": "read_only",
        },
        "bl": {
            "name": "电量",
            "kind": "state",
            "property_type": "apply",
            "format": "uint8",
            "unit": "%",
            "access": "read_only",
            "value_range": (0, 100, 1),
        },
    },
    "human_sensor": {
        "mv": {
            "name": "人体移动",
            "kind": "state",
            "property_type": "apply",
            "format": "boolean",
            "access": "read_only",
        },
        "alm": {
            "name": "防拆",
            "kind": "state",
            "property_type": "apply",
            "format": "boolean",
            "access": "read_only",
        },
        "luminance": {
            "name": "照度",
            "kind": "state",
            "property_type": "apply",
            "format": "float",
            "unit": "lx",
            "access": "read_only",
        },
        "bl": {
            "name": "电量",
            "kind": "state",
            "property_type": "apply",
            "format": "uint8",
            "unit": "%",
            "access": "read_only",
            "value_range": (0, 100, 1),
        },
    },
    "light_sensor": {
        "luminance": {
            "name": "照度",
            "kind": "state",
            "property_type": "apply",
            "format": "float",
            "unit": "lx",
            "access": "read_only",
        },
        "level": {
            "name": "等级",
            "kind": "state",
            "property_type": "apply",
            "format": "int",
            "access": "read_only",
        },
        "bl": {
            "name": "电量",
            "kind": "state",
            "property_type": "apply",
            "format": "uint8",
            "unit": "%",
            "access": "read_only",
            "value_range": (0, 100, 1),
        },
    },
    "sensor": {
        "t": {
            "name": "温度",
            "kind": "state",
            "property_type": "apply",
            "format": "float",
            "unit": "°C",
            "access": "read_only",
        },
        "h": {
            "name": "湿度",
            "kind": "state",
            "property_type": "apply",
            "format": "float",
            "unit": "%",
            "access": "read_only",
        },
        "luminance": {
            "name": "照度",
            "kind": "state",
            "property_type": "apply",
            "format": "float",
            "unit": "lx",
            "access": "read_only",
        },
        "level": {
            "name": "等级",
            "kind": "state",
            "property_type": "apply",
            "format": "int",
            "access": "read_only",
        },
    },
    "other": {
        "t": {
            "name": "温度",
            "kind": "state",
            "property_type": "apply",
            "format": "float",
            "unit": "°C",
            "access": "read_only",
        },
        "h": {
            "name": "湿度",
            "kind": "state",
            "property_type": "apply",
            "format": "float",
            "unit": "%",
            "access": "read_only",
        },
        "temp": {
            "name": "温度",
            "kind": "state",
            "property_type": "apply",
            "format": "float",
            "unit": "°C",
            "access": "read_only",
        },
        "luminance": {
            "name": "照度",
            "kind": "state",
            "property_type": "apply",
            "format": "float",
            "unit": "lx",
            "access": "read_only",
        },
        "curp": {
            "name": "当前功率",
            "kind": "state",
            "property_type": "apply",
            "format": "float",
            "unit": "W",
            "access": "read_only",
        },
        "iec": {
            "name": "阶段电量",
            "kind": "state",
            "property_type": "apply",
            "format": "float",
            "unit": "Wh",
            "access": "read_only",
        },
        "bl": {
            "name": "电量",
            "kind": "state",
            "property_type": "apply",
            "format": "uint8",
            "unit": "%",
            "access": "read_only",
            "value_range": (0, 100, 1),
        },
    },
}

