"""Safe entity_id migration helpers for Yeelight Pro registry reconciliation."""

from __future__ import annotations

from collections.abc import Mapping

from homeassistant.helpers.entity import async_generate_entity_id
from homeassistant.helpers import entity_registry as er

from .capabilities.registry import property_spec
from .const import DOMAIN
from .entity_candidates import EntityCandidate

_HELPER_ENTITY_TAILS = frozenset({"number", "select", "switch"})


def safe_entity_id_migration(
    registry_entry: er.RegistryEntry,
    candidate: EntityCandidate,
    *,
    current_entity_ids: set[str] | None,
) -> str | None:
    """Return a safer entity_id only for early integration-generated names."""
    if not _can_migrate_entity_id(registry_entry, candidate):
        return None
    domain = _registry_entry_domain(registry_entry)
    if domain is None:
        return None
    suggested = candidate.suggested_object_id
    if not isinstance(suggested, str) or not suggested.strip():
        return None
    current_entity_id = getattr(registry_entry, "entity_id", None)
    if not isinstance(current_entity_id, str):
        return None
    known_ids = set(current_entity_ids or ())
    known_ids.discard(current_entity_id)
    new_entity_id = async_generate_entity_id(f"{domain}.{{}}", suggested, known_ids)
    return new_entity_id if new_entity_id != current_entity_id else None


def registry_entity_ids(registry_entries: list[er.RegistryEntry]) -> set[str]:
    """Return current registry entity ids for conflict-safe migrations."""
    return _entity_ids_from_entries(registry_entries)


def all_registry_entity_ids(
    entity_registry: er.EntityRegistry,
    registry_entries: list[er.RegistryEntry],
) -> set[str]:
    """Return all known HA entity ids, falling back to scoped entries in tests."""
    entity_ids = _entity_ids_from_entries(registry_entries)
    entities = getattr(entity_registry, "entities", None)
    if isinstance(entities, Mapping):
        entity_ids.update(_entity_ids_from_entries(list(entities.values())))
    return entity_ids


def _entity_ids_from_entries(registry_entries: list[er.RegistryEntry]) -> set[str]:
    """Return entity ids from registry entry-like objects."""
    return {
        entity_id
        for entry in registry_entries
        if isinstance((entity_id := getattr(entry, "entity_id", None)), str)
    }


def _can_migrate_entity_id(
    registry_entry: er.RegistryEntry,
    candidate: EntityCandidate,
) -> bool:
    """Return true for registry ids generated by obsolete Yeelight templates."""
    if _registry_entry_disabled_by_user(registry_entry):
        return False
    if getattr(registry_entry, "disabled_by", None) not in {None, "integration"}:
        return False
    if getattr(registry_entry, "name", None) not in {None, ""}:
        return False
    entity_id = getattr(registry_entry, "entity_id", None)
    unique_id = getattr(registry_entry, "unique_id", None)
    if not isinstance(entity_id, str) or "." not in entity_id:
        return False
    if not isinstance(unique_id, str) or not unique_id.startswith(f"{DOMAIN}_"):
        return False
    object_id = entity_id.split(".", 1)[1]
    legacy_tail = _legacy_unique_id_tail(unique_id)
    if legacy_tail and object_id.endswith(f"_{legacy_tail}"):
        return True
    if _has_legacy_property_marker(registry_entry, candidate):
        return True
    return f"{DOMAIN}_{DOMAIN}_" in object_id


def _registry_entry_disabled_by_user(registry_entry: er.RegistryEntry) -> bool:
    """Return whether the registry entry was explicitly disabled by the user."""
    return getattr(registry_entry, "disabled_by", None) in {
        er.RegistryEntryDisabler.USER,
        "user",
    }


def _registry_entry_domain(registry_entry: er.RegistryEntry) -> str | None:
    """Return the HA entity domain for a registry entry."""
    domain = getattr(registry_entry, "domain", None)
    if isinstance(domain, str) and domain:
        return domain
    entity_id = getattr(registry_entry, "entity_id", "")
    if isinstance(entity_id, str) and "." in entity_id:
        return entity_id.split(".", 1)[0]
    return None


def _legacy_unique_id_tail(unique_id: str) -> str | None:
    """Return old channel/component suffixes that leaked into entity_id."""
    prefix = f"{DOMAIN}_"
    if not unique_id.startswith(prefix):
        return None
    parts = unique_id[len(prefix) :].split("_")
    if not parts:
        return None
    tail = parts[-1]
    if tail.isdigit():
        return tail
    if len(parts) >= 2 and parts[-2] in _HELPER_ENTITY_TAILS:
        return tail
    return None


def _has_legacy_property_marker(
    registry_entry: er.RegistryEntry,
    candidate: EntityCandidate,
) -> bool:
    """Return true when an active helper still exposes old property labels."""
    if not candidate.suggested_object_id:
        return False
    parsed = _property_from_helper_unique_id(getattr(registry_entry, "unique_id", None))
    if parsed is None:
        return False
    prop, full_name = parsed
    markers = _legacy_property_markers(prop, full_name)
    if not markers:
        return False
    texts = [
        getattr(registry_entry, "entity_id", None),
        getattr(registry_entry, "original_name", None),
    ]
    for text in texts:
        normalized = _normalized_words(text)
        if normalized and any(marker in normalized for marker in markers):
            return True
    return False


def _property_from_helper_unique_id(unique_id: object) -> tuple[str, str] | None:
    """Parse the official property key from helper unique_id suffixes."""
    if not isinstance(unique_id, str):
        return None
    prefix = f"{DOMAIN}_"
    if not unique_id.startswith(prefix):
        return None
    parts = unique_id[len(prefix) :].split("_")
    if len(parts) < 4 or parts[-1] not in _HELPER_ENTITY_TAILS:
        return None
    for start in range(len(parts) - 2, 0, -1):
        prop = "_".join(parts[start:-1])
        spec = property_spec(prop)
        if spec is not None:
            return (prop, spec.full_name)
    return None


def _legacy_property_markers(prop: str, full_name: str) -> tuple[str, ...]:
    """Return old raw markers that should no longer appear in HA ids/names."""
    markers: list[str] = []
    normalized_full_name = _normalized_words(full_name)
    if normalized_full_name and normalized_full_name != prop.lower():
        markers.append(normalized_full_name)
    if len(prop) >= 3:
        markers.append(prop.lower())
    return tuple(markers)


def _normalized_words(value: object) -> str | None:
    """Normalize entity ids and original names into comparable lowercase words."""
    if not isinstance(value, str):
        return None
    text = value.strip().lower().replace("_", " ")
    return " ".join(text.split()) or None
