"""Documented low-frequency Yeelight IoT catalog entries.

这些条目来自 docs/iot 的基础信息 CSV。运行时 registry 需要认识这些
组件/属性，实体投影仍只暴露有明确 HA 语义的能力。
"""

from __future__ import annotations

from .models import IoTComponentSpec, IoTPropertySpec


DOCUMENTED_COMPONENT_SPECS: tuple[IoTComponentSpec, ...] = (
    IoTComponentSpec(
        11,
        "runway panel",
        "跑道屏",
        "scene_panel",
        "global",
        "event",
        (
            "blp",
            "nightMode",
            "weather_hidden",
            "time_hidden",
            "temp_hidden",
            "keys_visible",
            "name",
            "icon",
            "io",
        ),
    ),
    IoTComponentSpec(
        27,
        "music control",
        "音乐组件",
        "other",
        "normal",
        None,
        ("mppm", "mpmp", "mpml", "mpmr", "name", "icon"),
    ),
    IoTComponentSpec(
        29,
        "audio control",
        "声音组件",
        "other",
        "normal",
        None,
        ("vol", "ntStart", "ntEnd"),
    ),
    IoTComponentSpec(
        36,
        "lift control",
        "可升降组件",
        "other",
        "normal",
        "number",
        ("height", "name", "icon", "io"),
    ),
    IoTComponentSpec(45, "mesh", "mesh组件", None, "global", None),
    IoTComponentSpec(46, "wifi", "wifi组件", None, "global", None),
    IoTComponentSpec(47, "ethernet", "以太网组件", None, "global", None),
    IoTComponentSpec(
        49,
        "backlight indicator",
        "背光指示灯组件",
        None,
        "global",
        "switch",
        ("blp", "nightMode"),
    ),
    IoTComponentSpec(50, "remote control management", "遥控器管理组件", None, "global"),
    IoTComponentSpec(51, "miHome", "米家组件", None, "global"),
    IoTComponentSpec(52, "midea", "美的组件", None, "global"),
    IoTComponentSpec(53, "haier", "海尔组件", None, "global"),
    IoTComponentSpec(54, "dual channel relay", "双路继电器组件", None, "global"),
    IoTComponentSpec(56, "wifi screen", "wifi屏组件", None, "global"),
    IoTComponentSpec(57, "mesh screen", "mesh屏组件", None, "global"),
    IoTComponentSpec(58, "combined rotary control", "组合旋钮组件", None, "global"),
    IoTComponentSpec(60, "undefined", "未定义子设备", "other", "normal"),
    IoTComponentSpec(61, "knob screen", "旋钮屏组件", None, "global"),
    IoTComponentSpec(62, "panorama screen", "全景屏组件", None, "global"),
    IoTComponentSpec(64, "single fire", "单火组件", None, "global"),
    IoTComponentSpec(70, "dali", "dali组件", None, "global"),
    IoTComponentSpec(
        73,
        "zonalShieldIlluminanceRadarSensor",
        "亮度雷达传感器(可屏蔽区段)",
        "light_sensor",
        "normal",
        "binary_sensor",
        (
            "mv",
            "li",
            "3rdPartySyncBitmask",
            "luminance",
            "sens_range",
            "lumi_setting",
            "delay_time",
            "name",
            "icon",
            "io",
            "sens_shield",
        ),
    ),
    IoTComponentSpec(74, "VirtualSwitch", "虚拟开关组件（全局）", None, "global"),
)


DOCUMENTED_PROPERTY_SPECS: tuple[IoTPropertySpec, ...] = (
    IoTPropertySpec("3rdPartySyncBitmask", "third party sync bitmask", "int", "读, 写", "config", "gateway"),
    IoTPropertySpec("name", "name", "string", "读, 写", "config", "gateway"),
    IoTPropertySpec("icon", "icon", "string", "读, 写", "config", "gateway"),
    IoTPropertySpec("io", "io type", "int", "读", "config", "device"),
    IoTPropertySpec("height", "height", "int", "读, 写", "application", "device"),
    IoTPropertySpec("vol", "volume", "int", "读, 写", "application", "device"),
    IoTPropertySpec("ntOn", "night mode on", "int", "读, 写", "config", "device"),
    IoTPropertySpec("ntStart", "night mode start", "int", "读, 写", "config", "device"),
    IoTPropertySpec("ntEnd", "night mode end", "int", "读, 写", "config", "device"),
    IoTPropertySpec("ntDelay", "night mode delay", "int", "读, 写", "config", "device"),
    IoTPropertySpec("ntScreenMode", "night screen mode", "int", "读, 写", "config", "device"),
    IoTPropertySpec("nightMode", "night mode", "jsonObj", "读, 写", "config", "device"),
    IoTPropertySpec("weather_hidden", "weather hidden", "bool", "读, 写", "config", "device"),
    IoTPropertySpec("time_hidden", "time hidden", "bool", "读, 写", "config", "device"),
    IoTPropertySpec("temp_hidden", "temperature hidden", "bool", "读, 写", "config", "device"),
    IoTPropertySpec("keys_visible", "keys visible", "int", "读, 写", "config", "device"),
    IoTPropertySpec("sens_range", "sense range", "int", "读, 写", "config", "device"),
    IoTPropertySpec("lumi_setting", "luminance setting", "int", "读, 写", "config", "device"),
    IoTPropertySpec("delay_time", "delay time", "int", "读, 写", "config", "device"),
    IoTPropertySpec("sens_shield", "sensing shield range", "int64", "读, 写", "config", "device"),
    IoTPropertySpec("mppm", "music player play mode", "int", "读, 写", "config", "device"),
    IoTPropertySpec("mpmp", "music player play pause", "bool", "读, 写", "config", "device"),
    IoTPropertySpec("mpml", "music player music list", "bool", "读, 写", "config", "device"),
    IoTPropertySpec("mpmr", "music player music rhythm", "int", "读, 写", "config", "device"),
    IoTPropertySpec("mp_keys", "multi-panel keys", "jsonObj", "读, 写", "config", "device"),
    IoTPropertySpec("mp_buttons", "multi-panel buttons", "jsonObj", "读, 写", "config", "device"),
    IoTPropertySpec("mp_devices", "multi-panel devices", "jsonObj", "读, 写", "config", "device"),
    IoTPropertySpec("mp_scenes", "multi-panel scenes", "jsonArray", "读, 写", "config", "device"),
    IoTPropertySpec("c_n_c", "component num config", "int", "读, 写", "config", "device", components=("basic",)),
    IoTPropertySpec("ct_rdy", "ct_rdy", "string", "读, 写", "config", "device"),
    IoTPropertySpec("dali_hds_cnt", "dali_hds_cnt", "int", "读, 写", "config", "gateway", components=("dali",)),
    IoTPropertySpec("dali_is_cnt", "dali_is_cnt", "int", "读, 写", "config", "gateway", components=("dali",)),
    IoTPropertySpec("dali_scb_cnt", "dali_scb_cnt", "int", "读, 写", "config", "gateway", components=("dali",)),
    IoTPropertySpec("ddt", "ddt", "string", "读, 写", "config", "gateway", components=("dali light",)),
    IoTPropertySpec("dev_alarm", "dev_alarm", "int", "读, 写", "config", "gateway", components=("basic", "dali")),
    IoTPropertySpec("deviceKey", "device key", "string", "读", "config", "device", components=("mesh",)),
    IoTPropertySpec("dntm", "device night mode", "jsonObj", "读, 写", "config", "device", components=("temp control",)),
    IoTPropertySpec("dt", "dt", "", "", "config", "device", components=("curtain",)),
    IoTPropertySpec("dver", "dver", "int", "读, 写", "application", "gateway", components=("dali",)),
    IoTPropertySpec("eip", "external IP", "string", "读", "config", "gateway", components=("wifi", "ethernet")),
    IoTPropertySpec("extend", "extend", "jsonObj", "读, 写", "config", "device", components=("wifi screen", "panorama screen")),
    IoTPropertySpec("fblck", "reset lock", "int", "读, 写", "config", "device", components=("basic",)),
    IoTPropertySpec("fbnum", "reset lock num", "int", "读, 写", "config", "device", components=("basic",)),
    IoTPropertySpec("gtin", "gtin", "int", "读, 写", "config", "gateway", components=("dali",)),
    IoTPropertySpec("hb_interval", "heart beat interval", "int", "读", "config", "device", components=("mesh",)),
    IoTPropertySpec("hk", "hk", "string", "读", "config", "gateway", components=("gateway",)),
    IoTPropertySpec("hr_all_nodes_sync_state", "haier all nodes sync state", "int", "读, 写", "config", "device", components=("haier",)),
    IoTPropertySpec("hr_all_scenes_sync_state", "haier all scenes sync state", "int", "读, 写", "config", "device", components=("haier",)),
    IoTPropertySpec("hr_login", "haier login", "int", "读", "config", "device", components=("haier",)),
    IoTPropertySpec("hrbk", "haier bind key", "string", "读, 写", "config", "gateway", components=("haier",)),
    IoTPropertySpec("hrdm", "haier domain", "string", "读, 写", "config", "gateway", components=("haier",)),
    IoTPropertySpec("hrln", "haier linked", "int", "读", "config", "device", components=("haier",)),
    IoTPropertySpec("hrpt", "haier port", "string", "读, 写", "config", "gateway", components=("haier",)),
    IoTPropertySpec("ip", "ip", "string", "读", "config", "device", components=("wifi", "ethernet")),
    IoTPropertySpec("jdef", "jog default", "int", "读, 写", "config", "device", components=("switch control",)),
    IoTPropertySpec("jen", "jog enable", "int", "读, 写", "config", "device", components=("switch control",)),
    IoTPropertySpec("jtm", "jog time", "int", "读, 写", "config", "device", components=("switch control",)),
    IoTPropertySpec("level_limit_rdy", "level_limit_rdy", "int", "读, 写", "config", "gateway", components=("brightness light", "color temperature light", "switch light")),
    IoTPropertySpec("life", "life", "int", "读, 写", "config", "backend", components=("basic",)),
    IoTPropertySpec("ltk", "local token", "string", "读", "config", "device", components=("wifi",)),
    IoTPropertySpec("mac", "mac", "string", "读", "config", "device", components=("mesh", "wifi", "ethernet")),
    IoTPropertySpec("mei_all_nodes_sync_state", "mei all nodes sync state", "int", "读, 写", "config", "gateway", components=("midea",)),
    IoTPropertySpec("mei_all_scenes_sync_state", "mei all scenes sync state", "int", "读, 写", "config", "gateway", components=("midea",)),
    IoTPropertySpec("mei_did", "mei did", "int64", "读", "config", "gateway", components=("midea",)),
    IoTPropertySpec("mei_info", "mei info", "string", "读, 写", "config", "gateway", components=("midea",)),
    IoTPropertySpec("mei_login", "mei login", "int", "读, 写", "config", "gateway", components=("midea",)),
    IoTPropertySpec("meibk", "mei bind key", "string", "读, 写", "config", "gateway", components=("midea",)),
    IoTPropertySpec("meiln", "mei linked", "int", "读", "config", "gateway", components=("midea",)),
    IoTPropertySpec("mfl", "mfl", "enum", "读", "config", "gateway", components=("gateway",)),
    IoTPropertySpec("mibk", "mi bind key", "string", "写", "config", "gateway", components=("miHome",)),
    IoTPropertySpec("micd", "mi country domain", "string", "读, 写", "config", "gateway", components=("miHome",)),
    IoTPropertySpec("midk", "mi device key", "string", "写", "config", "gateway", components=("miHome",)),
    IoTPropertySpec("miid", "mi did", "string", "写", "config", "gateway", components=("miHome",)),
    IoTPropertySpec("miln", "mi linked", "int", "读", "config", "gateway", components=("miHome",)),
    IoTPropertySpec("mimac", "mimac", "string", "读, 写", "config", "gateway", components=("miHome",)),
    IoTPropertySpec("mock", "mock", "int", "读, 写", "config", "gateway", components=("wireless switch channel", "switch control", "scene control button")),
    IoTPropertySpec("mp", "mutex power", "int", "读, 写", "config", "device", components=("dual channel relay",)),
    IoTPropertySpec("mp_nightmode", "multi-panel night mode", "jsonObj", "读, 写", "config", "device", components=("knob screen", "mesh screen")),
    IoTPropertySpec("pe", "pe", "", "", "config", "device", components=("curtain",)),
    IoTPropertySpec("pi", "pi", "", "", "config", "device", components=("curtain",)),
    IoTPropertySpec("plugins", "plugins", "jsonArray", "读, 写", "config", "gateway", components=("gateway",)),
    IoTPropertySpec("power_on_level", "power_on_level", "string", "读, 写", "config", "gateway", components=("dali light",)),
    IoTPropertySpec("psk", "psk", "string", "写", "config", "device", components=("wifi",)),
    IoTPropertySpec("retrans", "retrans num", "int", "读", "config", "device", components=("mesh",)),
    IoTPropertySpec("rl", "relay", "int", "读, 写", "config", "device", components=("mesh",)),
    IoTPropertySpec("rmt", "remote management", "string", "读", "config", "device", components=("remote control management",)),
    IoTPropertySpec("run_power", "run power", "int", "读, 写", "config", "backend", components=("basic",)),
    IoTPropertySpec("sbp", "switch power on boot", "int", "读, 写", "config", "device", components=("wireless switch channel",)),
    IoTPropertySpec("sdt", "device type after relay switch", "int", "读, 写", "config", "gateway", components=("wireless switch channel",)),
    IoTPropertySpec("showGroupDevices", "showGroupDevices", "boolean", "读, 写", "config", "app"),
    IoTPropertySpec("sonos_mgr", "sonos manager", "bool", "读, 写", "config", "gateway", components=("gateway",)),
    IoTPropertySpec("srb", "Switch rebound", "int", "读, 写", "config", "device", components=("VirtualSwitch",)),
    IoTPropertySpec("ssid", "ssid", "string", "读, 写", "config", "device", components=("wifi",)),
    IoTPropertySpec("support_fblck", "support reset lock", "bool", "读, 写", "config", "gateway", components=("basic",)),
    IoTPropertySpec("support_fbnum", "support reset lock num", "int", "读, 写", "config", "device"),
    IoTPropertySpec("support_rl", "support relay", "bool", "读", "config", "device", components=("mesh",)),
    IoTPropertySpec("system_failure_level", "system_failure_level", "string", "读, 写", "config", "gateway", components=("dali light",)),
    IoTPropertySpec("ttl", "time to live", "int", "读", "config", "device", components=("mesh",)),
    IoTPropertySpec("tx_power", "transmit power", "int", "读", "config", "device", components=("mesh",)),
)


__all__ = ["DOCUMENTED_COMPONENT_SPECS", "DOCUMENTED_PROPERTY_SPECS"]
