"""Documented Yeelight IoT product composition data.

数据整理自 ``docs/iot/基础信息_产品构成.csv``。运行时不读取 docs
目录，发布包必须自包含。
"""

from __future__ import annotations

from .models import IoTComponentSpec, IoTProductSpec


IOT_PRODUCT_SPECS: tuple[IoTProductSpec, ...] = (
    IoTProductSpec(1, "公开产品（无公开组件）", (), (), None, "不连接"),
    IoTProductSpec(2, "公开产品（无公开组件）", (), (), None, "不连接"),
    IoTProductSpec(3, "公开产品（无公开组件）", (), (), None, "不连接"),
    IoTProductSpec(14336, "公开产品（网关）", ("基础组件", "wifi组件", "以太网组件", "米家组件", "美的组件", "海尔组件"), ("网关",), "1", "直连", ("mesh协议",)),
    IoTProductSpec(14337, "公开产品（网关）", ("基础组件", "wifi组件", "以太网组件", "米家组件", "美的组件", "海尔组件"), ("网关",), "1", "直连", ("mesh协议",)),
    IoTProductSpec(133121, "公开产品（亮度灯）", ("基础组件", "mesh组件"), ("亮度灯",), "1", "mesh协议"),
    IoTProductSpec(133122, "公开产品（亮度灯）", ("基础组件", "mesh组件"), ("亮度灯",), None, "mesh协议"),
    IoTProductSpec(133123, "公开产品（亮度灯）", ("基础组件", "mesh组件"), ("亮度灯",), None, "mesh协议"),
    IoTProductSpec(133124, "公开产品（亮度灯）", ("基础组件", "mesh组件", "遥控器管理组件"), ("亮度灯",), None, "mesh协议"),
    IoTProductSpec(133125, "公开产品（亮度灯）", ("基础组件", "mesh组件"), ("亮度灯",), None, "mesh协议"),
    IoTProductSpec(133126, "公开产品（亮度灯）", ("基础组件", "mesh组件"), ("亮度灯",), None, "mesh协议"),
    IoTProductSpec(196608, "公开产品（色温灯）", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(196609, "公开产品（色温灯）", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(196610, "公开产品（色温灯）", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(196611, "公开产品（色温灯）", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(196612, "公开产品（色温灯）", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(196613, "公开产品（色温灯）", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(196614, "公开产品（色温灯）", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(196615, "公开产品（色温灯）", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198656, "公开产品（色温灯）", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198657, "公开产品（色温灯）", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198658, "公开产品（色温灯）", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198659, "公开产品（色温灯）", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198660, "公开产品（色温灯）", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198661, "公开产品（色温灯）", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198662, "公开产品（色温灯）", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198665, "公开产品（色温灯）", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198666, "公开产品（色温灯）", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198669, "公开产品（色温灯）", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198670, "公开产品（色温灯）", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198671, "公开产品（色温灯）", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198672, "公开产品（色温灯）", ("基础组件", "mesh组件", "遥控器管理组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198673, "公开产品（色温灯）", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198674, "公开产品（色温灯）", ("基础组件", "mesh组件", "遥控器管理组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198675, "公开产品（色温灯）", ("基础组件", "mesh组件"), ("色温灯",), None, "matter协议"),
    IoTProductSpec(262146, "公开产品（彩光灯）", ("基础组件", "mesh组件"), ("彩光灯",), None, "mesh协议"),
    IoTProductSpec(264193, "公开产品（彩光灯）", ("基础组件", "mesh组件"), ("彩光灯",), None, "mesh协议"),
    IoTProductSpec(264194, "公开产品（彩光灯）", ("基础组件", "mesh组件"), ("彩光灯",), None, "mesh协议"),
    IoTProductSpec(264195, "公开产品（彩光灯）", ("基础组件", "mesh组件"), ("彩光灯",), None, "mesh协议"),
    IoTProductSpec(264196, "公开产品（彩光灯）", ("基础组件", "mesh组件"), ("彩光灯",), None, "mesh协议"),
    IoTProductSpec(270336, "公开产品（无公开组件）", (), (), None, "不连接"),
    IoTProductSpec(395264, "公开产品（窗帘）", ("基础组件", "mesh组件"), ("窗帘",), "1", "mesh协议"),
    IoTProductSpec(395265, "公开产品（窗帘）", ("基础组件", "mesh组件"), ("窗帘",), None, "mesh协议"),
    IoTProductSpec(395266, "公开产品（窗帘）", ("基础组件", "mesh组件"), ("窗帘",), None, None),
    IoTProductSpec(395267, "公开产品（窗帘）", ("基础组件", "mesh组件"), ("窗帘",), None, None),
    IoTProductSpec(460800, "公开产品（开关）", ("基础组件", "mesh组件", "双路继电器组件"), ("开关",), "2", "mesh协议"),
    IoTProductSpec(460801, "公开产品（开关）", ("基础组件", "mesh组件", "双路继电器组件"), ("开关",), "2", None),
    IoTProductSpec(460802, "公开产品（开关）", ("基础组件", "mesh组件", "虚拟开关组件（全局）"), ("开关",), "2", "mesh协议"),
    IoTProductSpec(657408, "公开产品（未定义子设备）", ("基础组件", "mesh组件", "HVAC网关"), ("未定义子设备",), "动态", "mesh协议"),
    IoTProductSpec(854017, "公开产品（无线开关通道）", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "1", "mesh协议"),
    IoTProductSpec(854018, "公开产品（无线开关通道）", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "2", "mesh协议"),
    IoTProductSpec(854019, "公开产品（无线开关通道）", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "3", "mesh协议"),
    IoTProductSpec(854020, "公开产品（无线开关通道）", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "1", "mesh协议"),
    IoTProductSpec(854021, "公开产品（无线开关通道）", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "2", "mesh协议"),
    IoTProductSpec(854022, "公开产品（无线开关通道）", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "3", "mesh协议"),
    IoTProductSpec(854024, "公开产品（无线开关通道）", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "3", "mesh协议"),
    IoTProductSpec(854025, "公开产品（无线开关通道）", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "2", "mesh协议"),
    IoTProductSpec(854026, "公开产品（无线开关通道）", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "1", "mesh协议"),
    IoTProductSpec(854027, "公开产品（未定义子设备）", ("基础组件", "mesh组件", "背光指示灯组件"), ("未定义子设备",), "动态", "mesh协议"),
    IoTProductSpec(854028, "公开产品（无线开关通道）", ("基础组件", "mesh组件", "单火组件"), ("无线开关通道",), "1", "mesh协议"),
    IoTProductSpec(854029, "公开产品（无线开关通道）", ("基础组件", "mesh组件", "单火组件"), ("无线开关通道",), "2", "mesh协议"),
    IoTProductSpec(854030, "公开产品（无线开关通道）", ("基础组件", "mesh组件", "单火组件"), ("无线开关通道",), "3", "mesh协议"),
    IoTProductSpec(854031, "公开产品（无线开关通道）", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "1", "mesh协议"),
    IoTProductSpec(854032, "公开产品（无线开关通道）", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "2", "mesh协议"),
    IoTProductSpec(854033, "公开产品（无线开关通道）", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "3", "mesh协议"),
    IoTProductSpec(854038, "公开产品（无线开关通道）", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "1", None),
    IoTProductSpec(854039, "公开产品（无线开关通道）", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "2", None),
    IoTProductSpec(854040, "公开产品（无线开关通道）", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "3", None),
    IoTProductSpec(854041, "公开产品（无线开关通道）", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "4", None),
    IoTProductSpec(919553, "公开产品（角度色温灯）", ("基础组件", "mesh组件"), ("角度色温灯",), "1", "mesh协议"),
    IoTProductSpec(985089, "公开产品（空调）", ("基础组件", "mesh组件"), ("空调",), "1", "mesh协议"),
    IoTProductSpec(985090, "公开产品（空调）", ("基础组件", "mesh组件"), ("空调",), "1", "mesh协议"),
    IoTProductSpec(985091, "公开产品（空调）", ("基础组件", "mesh组件"), ("空调",), None, None),
    IoTProductSpec(1050624, "公开产品（开关）", ("基础组件", "mesh组件", "mesh屏组件"), ("开关",), "2", "mesh协议"),
    IoTProductSpec(1124352, "公开产品（音乐组件）", ("基础组件", "wifi组件", "以太网组件", "全景屏组件"), ("音乐组件",), None, "mesh协议"),
    IoTProductSpec(1312769, "公开产品（人在传感器、可升降组件）", ("基础组件", "mesh组件"), ("人在传感器", "可升降组件"), None, "mesh协议"),
    IoTProductSpec(1443840, "公开产品（梦幻帘）", ("基础组件", "mesh组件"), ("梦幻帘",), None, "mesh协议"),
    IoTProductSpec(1443841, "公开产品（梦幻帘）", ("基础组件", "mesh组件"), ("梦幻帘",), None, None),
    IoTProductSpec(1509378, "公开产品（情景按键、无线开关通道）", ("基础组件", "mesh组件", "跑道屏", "背光指示灯组件"), ("情景按键", "无线开关通道"), "6", "mesh协议", (), normal_component_counts=(("情景按键", 12), ("无线开关通道", 4))),
    IoTProductSpec(1574912, "公开产品（开关）", ("基础组件", "mesh组件", "旋钮屏组件"), ("开关",), "2", "mesh协议"),
    IoTProductSpec(8390656, "公开产品（情景按键）", ("基础组件", "mesh组件"), ("情景按键",), "8", "mesh协议"),
    IoTProductSpec(8390657, "公开产品（情景按键）", ("基础组件", "mesh组件"), ("情景按键",), "3", "mesh协议"),
    IoTProductSpec(8390658, "公开产品（情景按键）", ("基础组件", "mesh组件"), ("情景按键",), "2", "mesh协议"),
    IoTProductSpec(8390659, "公开产品（情景按键）", ("基础组件", "mesh组件"), ("情景按键",), "1", "mesh协议"),
    IoTProductSpec(8390660, "公开产品（情景按键）", ("基础组件", "mesh组件", "背光指示灯组件"), ("情景按键",), "6", "mesh协议"),
    IoTProductSpec(8390661, "公开产品（情景按键）", ("基础组件", "mesh组件"), ("情景按键",), "4", "mesh协议"),
    IoTProductSpec(8390662, "公开产品（情景按键）", ("基础组件", "mesh组件"), ("情景按键",), "6", "mesh协议"),
    IoTProductSpec(8390663, "公开产品（情景按键）", ("基础组件", "mesh组件", "背光指示灯组件"), ("情景按键",), "6", "mesh协议"),
    IoTProductSpec(8391424, "公开产品（情景按键）", ("基础组件", "mesh组件", "电池组件"), ("情景按键",), "8", "mesh协议"),
    IoTProductSpec(8391425, "公开产品（情景按键）", ("基础组件", "mesh组件", "电池组件"), ("情景按键",), "4", "mesh协议"),
    IoTProductSpec(8391427, "公开产品（情景按键）", ("基础组件", "mesh组件", "电池组件"), ("情景按键",), "6", "mesh协议"),
    IoTProductSpec(8391428, "公开产品（情景按键）", ("基础组件", "mesh组件", "电池组件"), ("情景按键",), "4", None),
    IoTProductSpec(8456192, "公开产品（人感传感器）", ("基础组件", "mesh组件"), ("人感传感器",), None, "mesh协议"),
    IoTProductSpec(8456448, "公开产品（人感传感器）", ("基础组件", "mesh组件", "电池组件"), ("人感传感器",), "1", "mesh协议"),
    IoTProductSpec(8456449, "公开产品（人在传感器）", ("基础组件", "mesh组件", "电池组件"), ("人在传感器",), None, "mesh协议"),
    IoTProductSpec(8521728, "公开产品（接触式传感器）", ("基础组件", "mesh组件"), ("接触式传感器",), None, "mesh协议"),
    IoTProductSpec(8522496, "公开产品（接触式传感器）", ("基础组件", "mesh组件", "电池组件"), ("接触式传感器",), "1", "mesh协议"),
    IoTProductSpec(8653058, "公开产品（旋钮开关）", ("基础组件", "mesh组件", "电池组件"), ("旋钮开关",), None, "mesh协议"),
    IoTProductSpec(8784640, "公开产品（人体红外传感器）", ("基础组件", "mesh组件", "电池组件"), ("人体红外传感器",), None, "mesh协议"),
    IoTProductSpec(8849408, "公开产品（环境光传感器）", ("基础组件", "mesh组件"), ("环境光传感器",), None, "mesh协议"),
    IoTProductSpec(8980736, "公开产品（情景按键）", ("基础组件", "mesh组件", "组合旋钮组件", "电池组件"), ("情景按键",), "4", "mesh协议"),
    IoTProductSpec(9040618, "公开产品（全局组件）", ("基础组件", "mesh组件"), (), None, None),
    IoTProductSpec(9046017, "公开产品（光照传感器2）", ("基础组件", "mesh组件"), ("光照传感器2",), None, "mesh协议"),
    IoTProductSpec(16787456, "公开产品（开关）", ("基础组件", "wifi组件", "wifi屏组件"), ("开关",), "2", "mesh协议"),
    IoTProductSpec(16787457, "公开产品（无公开组件）", (), (), None, None),
    IoTProductSpec(17000000, "公开产品（亮度灯、温控器组件）", ("基础组件", "mesh组件", "遥控器管理组件"), ("亮度灯", "温控器组件"), "2", "mesh协议"),
    IoTProductSpec(17000001, "公开产品（网关）", ("基础组件", "wifi组件", "以太网组件", "米家组件", "美的组件", "海尔组件"), ("网关",), None, "直连", ("dali协议",)),
    IoTProductSpec(17000002, "公开产品（开关灯）", ("基础组件", "dali灯组件", "dali能量组件"), ("开关灯",), None, "dali协议"),
    IoTProductSpec(17000003, "公开产品（亮度灯）", ("基础组件", "dali灯组件", "dali能量组件"), ("亮度灯",), None, "dali协议"),
    IoTProductSpec(17000004, "公开产品（色温灯）", ("基础组件", "dali灯组件", "dali能量组件"), ("色温灯",), None, "dali协议"),
    IoTProductSpec(17000005, "公开产品（dali情景按键、dali人感传感器、dali光感传感器）", ("dali组件", "基础组件"), ("dali情景按键", "dali人感传感器", "dali光感传感器"), "32", "dali协议"),
    IoTProductSpec(17000007, "公开产品（网关、音乐组件、开关）", ("基础组件", "wifi组件", "以太网组件", "米家组件", "全景屏组件"), ("网关", "音乐组件", "开关"), "4", "直连", ("mesh协议", "matter协议"), normal_component_counts=(("开关", 2),)),
)

IOT_MD_ONLY_PRODUCT_SPECS: tuple[IoTProductSpec, ...] = (
    IoTProductSpec(17000012, "公开产品（色温灯、人在传感器）", (), ("色温灯", "人在传感器"), None, None),
    IoTProductSpec(17000013, "公开产品（色温灯、彩光灯、TOF传感器）", (), ("色温灯", "彩光灯", "TOF传感器"), None, None),
)

IOT_MD_ONLY_COMPONENT_SPECS = (
    # LAN protocol 2.14/2.18 documents TOF as a split LAN topology node.
    # It is not in 基础信息_组件列表.csv, so keep it scoped to product fallback.
    IoTComponentSpec(
        2052,
        "tof sensor",
        "TOF传感器",
        "other",
        "normal",
        "event",
        (),
        ("handwave",),
    ),
)

__all__ = [
    "IOT_MD_ONLY_COMPONENT_SPECS",
    "IOT_MD_ONLY_PRODUCT_SPECS",
    "IOT_PRODUCT_SPECS",
]
