"""Documented Yeelight IoT product composition data.

数据整理自 ``docs/iot/基础信息_产品构成.csv``。运行时不读取 docs
目录，发布包必须自包含。
"""

from __future__ import annotations

from .models import IoTProductSpec


IOT_PRODUCT_SPECS: tuple[IoTProductSpec, ...] = (
    IoTProductSpec(1, "Ray 桌面氛围塔灯 matter方案，接入Yeelight Station", (), (), None, "不连接"),
    IoTProductSpec(2, "matter版幻彩灯带，接入Yeelight Station", (), (), None, "不连接"),
    IoTProductSpec(3, "【正式版】Ray 桌面氛围塔灯 matter方案，接入Yeelight Station1", (), (), None, "不连接"),
    IoTProductSpec(14336, "Yeelight Pro S20 蓝牙Mesh网关", ("基础组件", "wifi组件", "以太网组件", "米家组件", "美的组件", "海尔组件"), ("网关",), "1", "直连", ("mesh协议",)),
    IoTProductSpec(14337, "Yeelight ProS20 新网关", ("基础组件", "wifi组件", "以太网组件", "米家组件", "美的组件", "海尔组件"), ("网关",), "1", "直连", ("mesh协议",)),
    IoTProductSpec(133121, "Yeelight 青空灯", ("基础组件", "mesh组件"), ("亮度灯",), "1", "mesh协议"),
    IoTProductSpec(133122, "亮度灯通用固件 - 拨码开关版", ("基础组件", "mesh组件"), ("亮度灯",), None, "mesh协议"),
    IoTProductSpec(133123, "Yeelight Pro P20 青空灯", ("基础组件", "mesh组件"), ("亮度灯",), None, "mesh协议"),
    IoTProductSpec(133124, "亮度灯通用固件 - 拨码遥控版", ("基础组件", "mesh组件", "遥控器管理组件"), ("亮度灯",), None, "mesh协议"),
    IoTProductSpec(133125, "亮度灯固件-DC模块", ("基础组件", "mesh组件"), ("亮度灯",), None, "mesh协议"),
    IoTProductSpec(133126, "单亮度灯", ("基础组件", "mesh组件"), ("亮度灯",), None, "mesh协议"),
    IoTProductSpec(196608, "商照色温mesh插电筒灯", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(196609, "商照色温mesh插电筒灯(冷暖)", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(196610, "商照色温mesh插电灯带", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(196611, "色温mesh插电筒灯", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(196612, "擎洲亮度色温灯", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(196613, "Yeelight 商照 JFMY 方形 嵌入式防眩射灯", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(196614, "万耐特冷暖色温灯", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(196615, "兆驰亮度色温灯", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198656, "色温筒射灯电源", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198657, "色温筒射灯电源(冷暖)", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198658, "Yeelight Pro S20 色温灯带", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198659, "Yeelight Pro S20 蓝牙Mesh球泡", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198660, "Yeelight Pro 商照 智能调光调色矿棉板面板灯", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198661, "Yeelight Pro M20 嵌入式筒灯", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198662, "Yeleight Pro M20 球泡灯", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198665, "Yeelight Pro S20 面板灯 3030", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198666, "色温灯通用固件 - CW", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198669, "色温灯通用固件 - 拨码开关版", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198670, "色温灯通用固件", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198671, "Yeelight商照X系列智能橱柜灯电源", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198672, "青空灯", ("基础组件", "mesh组件", "遥控器管理组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198673, "色温灯固件-DC模块", ("基础组件", "mesh组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198674, "色温灯通用固件 - 拨码遥控版", ("基础组件", "mesh组件", "遥控器管理组件"), ("色温灯",), None, "mesh协议"),
    IoTProductSpec(198675, "NFC色温灯固件", ("基础组件", "mesh组件"), ("色温灯",), None, "matter协议"),
    IoTProductSpec(262146, "Yeelight Pro 商照 低压彩光灯带智能DCDC模块120W", ("基础组件", "mesh组件"), ("彩光灯",), None, "mesh协议"),
    IoTProductSpec(264193, "色彩灯通用固件 - RGBW", ("基础组件", "mesh组件"), ("彩光灯",), None, "mesh协议"),
    IoTProductSpec(264194, "色彩灯固件-DC模块-RGB", ("基础组件", "mesh组件"), ("彩光灯",), None, "mesh协议"),
    IoTProductSpec(264195, "色彩灯固件-DC模块-WRGB", ("基础组件", "mesh组件"), ("彩光灯",), None, "mesh协议"),
    IoTProductSpec(264196, "色彩灯固件-DC模块-CWRGB", ("基础组件", "mesh组件"), ("彩光灯",), None, "mesh协议"),
    IoTProductSpec(270336, "Yeelight Cube smart desk lamp", (), (), None, "不连接"),
    IoTProductSpec(395264, "Yeelight Pro S20 窗帘电机", ("基础组件", "mesh组件"), ("窗帘",), "1", "mesh协议"),
    IoTProductSpec(395265, "YL-商照-智能卷帘电机", ("基础组件", "mesh组件"), ("窗帘",), None, "mesh协议"),
    IoTProductSpec(395266, "E系列卷帘电机-卷帘；E系列卷帘电机-柔纱帘；E系列卷帘电机-日夜蜂巢帘；", ("基础组件", "mesh组件"), ("窗帘",), None, None),
    IoTProductSpec(395267, "E系列窗帘电机", ("基础组件", "mesh组件"), ("窗帘",), None, None),
    IoTProductSpec(460800, "Yeelight Pro S20 双路控制模块（MESH版）", ("基础组件", "mesh组件", "双路继电器组件"), ("开关",), "2", "mesh协议"),
    IoTProductSpec(460801, "可控制两路供电输出的智能开关；SKU：YLP-S20双路控制模块-标准版-白色", ("基础组件", "mesh组件", "双路继电器组件"), ("开关",), "2", None),
    IoTProductSpec(460802, "自回弹虚拟双路开关", ("基础组件", "mesh组件", "虚拟开关组件（全局）"), ("开关",), "2", "mesh协议"),
    IoTProductSpec(657408, "Yeelight Pro S21 VRF空调温控器", ("基础组件", "mesh组件", "HVAC网关"), ("未定义子设备",), "动态", "mesh协议"),
    IoTProductSpec(854017, "Yeelight Pro S21 智能墙壁开关-单键", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "1", "mesh协议"),
    IoTProductSpec(854018, "Yeelight Pro S21 智能墙壁开关-双键", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "2", "mesh协议"),
    IoTProductSpec(854019, "Yeelight Pro S21 智能墙壁开关-三键", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "3", "mesh协议"),
    IoTProductSpec(854020, "Yeelight商业M系列智能复合开关-单键", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "1", "mesh协议"),
    IoTProductSpec(854021, "Yeelight商业M系列智能复合开关-双键", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "2", "mesh协议"),
    IoTProductSpec(854022, "Yeelight商业M系列智能复合开关-三键", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "3", "mesh协议"),
    IoTProductSpec(854024, "Yeelight Pro M20 智能开关-三键", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "3", "mesh协议"),
    IoTProductSpec(854025, "Yeelight Pro M20 智能开关-双键", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "2", "mesh协议"),
    IoTProductSpec(854026, "Yeelight Pro M20 智能开关-单键", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "1", "mesh协议"),
    IoTProductSpec(854027, "Yeelight Pro E20 智能开关", ("基础组件", "mesh组件", "背光指示灯组件"), ("未定义子设备",), "动态", "mesh协议"),
    IoTProductSpec(854028, "E系列单火智能开关-单键", ("基础组件", "mesh组件", "单火组件"), ("无线开关通道",), "1", "mesh协议"),
    IoTProductSpec(854029, "E系列单火智能开关-双键", ("基础组件", "mesh组件", "单火组件"), ("无线开关通道",), "2", "mesh协议"),
    IoTProductSpec(854030, "E系列单火智能开关-三键", ("基础组件", "mesh组件", "单火组件"), ("无线开关通道",), "3", "mesh协议"),
    IoTProductSpec(854031, "E系列零火智能开关-单键", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "1", "mesh协议"),
    IoTProductSpec(854032, "E系列零火智能开关-双键", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "2", "mesh协议"),
    IoTProductSpec(854033, "E系列零火智能开关-三键", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "3", "mesh协议"),
    IoTProductSpec(854038, "智能开关-单键 (rtl8762e版)", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "1", None),
    IoTProductSpec(854039, "智能开关-双键 (rtl8762e版)", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "2", None),
    IoTProductSpec(854040, "智能开关-三键 (rtl8762e版)", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "3", None),
    IoTProductSpec(854041, "智能开关-四键 (rtl8762e版)", ("基础组件", "mesh组件", "背光指示灯组件"), ("无线开关通道",), "4", None),
    IoTProductSpec(919553, "Yeelight Pro P20 数字变焦射灯 3寸", ("基础组件", "mesh组件"), ("角度色温灯",), "1", "mesh协议"),
    IoTProductSpec(985089, "Yeelight商业X系列空调温控器", ("基础组件", "mesh组件"), ("空调",), "1", "mesh协议"),
    IoTProductSpec(985090, "商照Q系列空调温控器", ("基础组件", "mesh组件"), ("空调",), "1", "mesh协议"),
    IoTProductSpec(985091, "风管机温控器（小超人）", ("基础组件", "mesh组件"), ("空调",), None, None),
    IoTProductSpec(1050624, "屏幕控制面板mesh版", ("基础组件", "mesh组件", "mesh屏组件"), ("开关",), "2", "mesh协议"),
    IoTProductSpec(1124352, "P20全景屏", ("基础组件", "wifi组件", "以太网组件", "全景屏组件"), ("音乐组件",), None, "mesh协议"),
    IoTProductSpec(1312769, "字节跳动升降桌", ("基础组件", "mesh组件"), ("人在传感器", "可升降组件"), None, "mesh协议"),
    IoTProductSpec(1443840, "Yeelight Pro S系列梦幻窗帘电机", ("基础组件", "mesh组件"), ("梦幻帘",), None, "mesh协议"),
    IoTProductSpec(1443841, "E系列卷帘电机-百叶帘；E系列卷帘电机-香格里拉帘；", ("基础组件", "mesh组件"), ("梦幻帘",), None, None),
    IoTProductSpec(1509378, "S系列情景开关", ("基础组件", "mesh组件", "跑道屏", "背光指示灯组件"), ("情景按键", "无线开关通道"), "6", "mesh协议"),
    IoTProductSpec(1574912, "S系列墙面旋钮屏开关", ("基础组件", "mesh组件", "旋钮屏组件"), ("开关",), "2", "mesh协议"),
    IoTProductSpec(8390656, "Yeelight Pro S20系列8键情景开关(单火版)", ("基础组件", "mesh组件"), ("情景按键",), "8", "mesh协议"),
    IoTProductSpec(8390657, "Yeelight商业Q系列智能情景开关-三键", ("基础组件", "mesh组件"), ("情景按键",), "3", "mesh协议"),
    IoTProductSpec(8390658, "Yeelight商业Q系列智能情景开关-双键", ("基础组件", "mesh组件"), ("情景按键",), "2", "mesh协议"),
    IoTProductSpec(8390659, "Yeelight商业Q系列智能情景开关-单键", ("基础组件", "mesh组件"), ("情景按键",), "1", "mesh协议"),
    IoTProductSpec(8390660, "Yeelight Pro S21 智能情景开关-六键", ("基础组件", "mesh组件", "背光指示灯组件"), ("情景按键",), "6", "mesh协议"),
    IoTProductSpec(8390661, "Yeelight商业Q系列智能情景开关-四键", ("基础组件", "mesh组件"), ("情景按键",), "4", "mesh协议"),
    IoTProductSpec(8390662, "Yeelight Pro干接点输入模块", ("基础组件", "mesh组件"), ("情景按键",), "6", "mesh协议"),
    IoTProductSpec(8390663, "E20智能情景面板-六键(零火版)", ("基础组件", "mesh组件", "背光指示灯组件"), ("情景按键",), "6", "mesh协议"),
    IoTProductSpec(8391424, "Yeelight Pro S20系列8键情景开关(贴装版)", ("基础组件", "mesh组件", "电池组件"), ("情景按键",), "8", "mesh协议"),
    IoTProductSpec(8391425, "Yeelight Pro S20系列4键情景开关(贴装版)", ("基础组件", "mesh组件", "电池组件"), ("情景按键",), "4", "mesh协议"),
    IoTProductSpec(8391427, "E20智能情景面板-六键(纽扣电池版）", ("基础组件", "mesh组件", "电池组件"), ("情景按键",), "6", "mesh协议"),
    IoTProductSpec(8391428, "D系列智能情景面板-四键（纽扣电池版）", ("基础组件", "mesh组件", "电池组件"), ("情景按键",), "4", None),
    IoTProductSpec(8456192, "擎洲人体传感器", ("基础组件", "mesh组件"), ("人感传感器",), None, "mesh协议"),
    IoTProductSpec(8456448, "Yeelight Pro S20 人体传感器", ("基础组件", "mesh组件", "电池组件"), ("人感传感器",), "1", "mesh协议"),
    IoTProductSpec(8456449, "Yeelight Pro P20 人在传感器", ("基础组件", "mesh组件", "电池组件"), ("人在传感器",), None, "mesh协议"),
    IoTProductSpec(8521728, "Yeelight商业Q系列智能插卡取电器（低频）", ("基础组件", "mesh组件"), ("接触式传感器",), None, "mesh协议"),
    IoTProductSpec(8522496, "Yeelight Pro S20 门窗传感器", ("基础组件", "mesh组件", "电池组件"), ("接触式传感器",), "1", "mesh协议"),
    IoTProductSpec(8653058, "Yeelight Pro M20 旋钮开关", ("基础组件", "mesh组件", "电池组件"), ("旋钮开关",), None, "mesh协议"),
    IoTProductSpec(8784640, "Yeelight Pro S21 人体红外传感器", ("基础组件", "mesh组件", "电池组件"), ("人体红外传感器",), None, "mesh协议"),
    IoTProductSpec(8849408, "环境光传感器", ("基础组件", "mesh组件"), ("环境光传感器",), None, "mesh协议"),
    IoTProductSpec(8980736, "E系列旋钮开关", ("基础组件", "mesh组件", "组合旋钮组件", "电池组件"), ("情景按键",), "4", "mesh协议"),
    IoTProductSpec(9040618, "人在传感器（吸顶）；光照度+雷达", ("基础组件", "mesh组件"), (), None, None),
    IoTProductSpec(9046017, "迈睿人在光照度传感器", ("基础组件", "mesh组件"), ("光照传感器2",), None, "mesh协议"),
    IoTProductSpec(16787456, "Yeelight Pro S21 全面屏开关", ("基础组件", "wifi组件", "wifi屏组件"), ("开关",), "2", "mesh协议"),
    IoTProductSpec(16787457, "Yeelight FUN 产品线-Matter 设备-量产版本，采用正式VID：0x1312；PID：0x0001", (), (), None, None),
    IoTProductSpec(17000000, "浴霸", ("基础组件", "mesh组件", "遥控器管理组件"), ("亮度灯", "温控器组件"), "2", "mesh协议"),
    IoTProductSpec(17000001, "DALI网关", ("基础组件", "wifi组件", "以太网组件", "米家组件", "美的组件", "海尔组件"), ("网关",), None, "直连", ("dali协议",)),
    IoTProductSpec(17000002, "dali开关灯", ("基础组件", "dali灯组件", "dali能量组件"), ("开关灯",), None, "dali协议"),
    IoTProductSpec(17000003, "dali亮度灯", ("基础组件", "dali灯组件", "dali能量组件"), ("亮度灯",), None, "dali协议"),
    IoTProductSpec(17000004, "dali色温灯", ("基础组件", "dali灯组件", "dali能量组件"), ("色温灯",), None, "dali协议"),
    IoTProductSpec(17000005, "dali输入设备", ("dali组件", "基础组件"), ("dali情景按键", "dali人感传感器", "dali光感传感器"), "32", "dali协议"),
    IoTProductSpec(17000007, "6.9寸智慧屏", ("基础组件", "wifi组件", "以太网组件", "米家组件", "全景屏组件"), ("网关", "音乐组件", "开关"), "4", "直连", ("mesh协议", "matter协议")),
)


__all__ = ["IOT_PRODUCT_SPECS"]
