"""Release-facing stale-claim denylist for Yeelight Pro preflight."""

from __future__ import annotations

STALE_DOC_CLAIMS = {
    "15 个平台",
    "15 个平台实体",
    "15 platforms",
    "通过 85 个测试",
    "通过 128 个测试",
    "通过 189 个测试",
    "通过 196 个测试",
    "通过 198 个测试",
    "通过 200 个测试",
    "通过 204 个测试",
    "通过 207 个测试",
    "通过 210 个测试",
    "通过 217 个测试",
    "通过 219 个测试",
    "通过 221 个测试",
    "通过 225 个测试",
    "通过 229 个测试",
    "通过 232 个测试",
    "passes with 85 tests",
    "passes with 128 tests",
    "passes with 189 tests",
    "passes with 196 tests",
    "passes with 198 tests",
    "passes with 200 tests",
    "passes with 204 tests",
    "passes with 207 tests",
    "passes with 210 tests",
    "passes with 217 tests",
    "passes with 219 tests",
    "passes with 221 tests",
    "passes with 225 tests",
    "128 passed",
    "189 passed",
    "196 passed",
    "198 passed",
    "200 passed",
    "204 passed",
    "207 passed",
    "210 passed",
    "217 passed",
    "219 passed",
    "221 passed",
    "225 passed",
    "229 passed",
    "232 passed",
    "61 files",
    "62 files",
    "64 files",
    "65 files",
    "56%",
    "57%",
    "62%",
    "63%",
    "64%",
    "100%",
    "全部支持",
    "fully supported",
    "all supported",
    "SSE 已支持",
    "SSE 已实现",
    "SSE is implemented",
    "SSE support is implemented",
    "实时推送已实现",
    "OAuth 已支持",
    "OAuth 已实现",
    "OAuth is implemented",
    "OAuth support is implemented",
    "本地网关已支持",
    "本地网关已实现",
    "local gateway is implemented",
    "local gateway support is implemented",
    "live WebSocket is implemented",
    "live WebSocket updates are implemented",
    "all analytics APIs are implemented",
    "all analytics endpoints are implemented",
    "analytics runtime is enabled by default",
    "analytics raw payload is persisted",
    "analytics raw payloads are persisted",
    "analytics full history is persisted",
    "all data-analysis APIs are implemented",
    "数据分析全部接口已实现",
    "数据分析默认启用",
    "数据分析原始数据已持久化",
    "数据分析完整历史已持久化",
    "家庭转移已支持",
    "家庭转移已实现",
    "house transfer is implemented",
    "house transfer support is implemented",
    "device import filter deletes existing entities",
    "device import filter hides existing entities",
    "device import filter removes existing entities",
    "device import filter cleans existing entities",
    "device import filter cleans up existing entities",
    "device import filter cleans device registry",
    "device import filter migrates existing entities",
    "设备导入过滤会删除既有实体",
    "设备导入过滤会隐藏既有实体",
    "设备导入过滤会清理既有实体",
    "设备导入过滤会迁移既有实体",
    "设备导入过滤会清理设备注册表",
    "HACS 发布完成",
    "HACS publication complete",
    "已通过 HACS 网站提交",
    "published to HACS",
    "集成已准备好发布到 HACS",
    "ready for HACS publication",
    "准备发布 ✅",
    "cp -R custom_components/yeelight_pro",
    "cp -r custom_components/yeelight_pro",
}
STALE_DOC_PATTERNS = {
    r"15\s+platforms",
    r"15\s*个",
    r"15\s*平台",
    r"85\s+passed",
    r"85\s+tests?",
    r"85\s*个测试",
    r"128\s+passed",
    r"128\s+tests?",
    r"128\s*个测试",
    r"189\s+passed",
    r"189\s+tests?",
    r"189\s*个测试",
    r"196\s+passed",
    r"196\s+tests?",
    r"196\s*个测试",
    r"198\s+passed",
    r"198\s+tests?",
    r"198\s*个测试",
    r"200\s+passed",
    r"200\s+tests?",
    r"200\s*个测试",
    r"204\s+passed",
    r"204\s+tests?",
    r"204\s*个测试",
    r"207\s+passed",
    r"207\s+tests?",
    r"207\s*个测试",
    r"210\s+passed",
    r"210\s+tests?",
    r"210\s*个测试",
    r"217\s+passed",
    r"217\s+tests?",
    r"217\s*个测试",
    r"219\s+passed",
    r"219\s+tests?",
    r"219\s*个测试",
    r"221\s+passed",
    r"221\s+tests?",
    r"221\s*个测试",
    r"225\s+passed",
    r"225\s+tests?",
    r"225\s*个测试",
    r"229\s+passed",
    r"229\s+tests?",
    r"229\s*个测试",
    r"232\s+passed",
    r"232\s+tests?",
    r"232\s*个测试",
    r"\d+\s+passed",
    r"\d+\s+tests?",
    r"(?:通过|共)\s*\d+\s*个测试",
    r"\d+\s*个测试",
    r"61\s+files",
    r"62\s+files",
    r"64\s+files",
    r"65\s+files",
    r"\d+\s+files",
    r"56\s*%",
    r"57\s*%",
    r"62\s*%",
    r"63\s*%",
    r"64\s*%",
    r"\d+\s*%",
    r"SSE\s*已",
    r"SSE\s+(?:is|support is)\s+implemented",
    r"实时更新.*已",
    r"OAuth.*已(?:支持|实现|启用|可用)",
    r"OAuth\s+(?:is|support is)\s+implemented",
    r"local gateway.*已",
    r"local gateway(?: support)? is implemented",
    r"live WebSocket\s+(?:is|updates are)\s+implemented",
    r"(?:all|full|complete).{0,30}(?:analytics|data-analysis).{0,30}(?:implemented|supported)",
    r"(?:analytics|data-analysis).{0,30}(?:enabled by default|auto(?:matic)? polling|raw payloads? (?:is |are )?persisted|full history (?:is )?persisted)",
    r"数据分析.{0,20}(?:全部|完整|默认启用|自动轮询|原始数据.{0,8}持久化)",
    r"本地网关.*已",
    r"家庭转移.*已(?:支持|实现|启用|可用)",
    r"house transfer\s+(?:is|support is)\s+implemented",
    r"device import filter.{0,40}(?:will|automatically|supports?|implemented).{0,20}"
    r"(?:delete|remove|hide|clean(?:s| up)?|migrate).{0,40}existing entit",
    r"device import filter.{0,40}(?:will|automatically|supports?|implemented).{0,20}"
    r"clean(?:s| up)?.{0,40}device registry",
    r"设备导入过滤.{0,20}(?:会|将|自动|已(?:支持|实现)|支持).{0,8}"
    r"(?:删除|禁用|隐藏|清理|迁移).{0,20}(?:既有|现有).*实体",
    r"设备导入过滤.{0,20}(?:会|将|自动|已(?:支持|实现)|支持).{0,8}"
    r"清理.{0,20}设备注册表",
    r"cp\s+-[Rr]\s+custom_components/yeelight_pro",
}
