"""Release-facing stale-claim denylist for Yeelight Pro preflight."""

from __future__ import annotations

STALE_DOC_CLAIMS = {
    "15 个平台",
    "15 个平台实体",
    "15 platforms",
    "通过 85 个测试",
    "通过 128 个测试",
    "通过 189 个测试",
    "通过 196 个测试",
    "通过 198 个测试",
    "通过 200 个测试",
    "通过 204 个测试",
    "通过 207 个测试",
    "通过 210 个测试",
    "通过 217 个测试",
    "通过 219 个测试",
    "通过 221 个测试",
    "通过 225 个测试",
    "通过 229 个测试",
    "通过 232 个测试",
    "passes with 85 tests",
    "passes with 128 tests",
    "passes with 189 tests",
    "passes with 196 tests",
    "passes with 198 tests",
    "passes with 200 tests",
    "passes with 204 tests",
    "passes with 207 tests",
    "passes with 210 tests",
    "passes with 217 tests",
    "passes with 219 tests",
    "passes with 221 tests",
    "passes with 225 tests",
    "128 passed",
    "189 passed",
    "196 passed",
    "198 passed",
    "200 passed",
    "204 passed",
    "207 passed",
    "210 passed",
    "217 passed",
    "219 passed",
    "221 passed",
    "225 passed",
    "229 passed",
    "232 passed",
    "61 files",
    "62 files",
    "64 files",
    "65 files",
    "56%",
    "57%",
    "62%",
    "63%",
    "64%",
    "100%",
    "全部支持",
    "fully supported",
    "all supported",
    "SSE 已支持",
    "SSE 已实现",
    "SSE is implemented",
    "SSE support is implemented",
    "SSE runtime",
    "SSE transport",
    "SSE event notifications",
    "SSE live updates",
    "SSE subscription",
    "SSE 推送",
    "SSE 事件通知",
    "SSE 实时更新",
    "EventSource",
    "Server-Sent Events",
    "server-sent events",
    "WebSocket/SSE",
    "WebSocket / SSE",
    "WebSocket or SSE",
    "WebSocket and SSE",
    "WebSocket + SSE",
    "WebSocket 或 SSE",
    "WebSocket 和 SSE",
    "WebSocket 加 SSE",
    "WebSocket / SSE / subscription 尚未作为运行时能力完成",
    "实时推送已实现",
    "OAuth 已支持",
    "OAuth 已实现",
    "OAuth is implemented",
    "OAuth support is implemented",
    "Home Assistant OAuth 登录是否仍作为扫码登录之外的目标",
    "Home Assistant OAuth 取舍",
    "Home Assistant OAuth product approval",
    "Decide whether Home Assistant OAuth should still be a first-party release goal or remain replaced by APP scan-login",
    "OAuth runtime task: wire the existing no-network OAuth contract into Home Assistant config flow",
    "本地网关已支持",
    "本地网关已实现",
    "local gateway is implemented",
    "local gateway support is implemented",
    "mDNS discovery is implemented",
    "automatic local gateway discovery is implemented",
    "local gateway discovery is enabled by default",
    "本地网关 mDNS 已实现",
    "自动本地网关发现已实现",
    "本地网关发现默认启用",
    "live WebSocket is implemented",
    "live WebSocket updates are implemented",
    "家庭转移已支持",
    "家庭转移已实现",
    "house transfer is implemented",
    "house transfer support is implemented",
    "device import filter deletes existing entities",
    "device import filter hides existing entities",
    "device import filter removes existing entities",
    "device import filter cleans existing entities",
    "device import filter cleans up existing entities",
    "device import filter cleans device registry",
    "device import filter migrates existing entities",
    "device picker requires device list",
    "device picker requires the device list",
    "device picker blocks setup when device list fails",
    "device picker blocks setup when loading devices fails",
    "device list load failure blocks setup",
    "device list load failure blocks configuration",
    "device picker is setup-only",
    "device picker only works during setup",
    "device picker cannot be changed from options",
    "options cannot change selected devices",
    "options cannot reopen the device picker",
    "设备导入过滤会删除既有实体",
    "设备导入过滤会隐藏既有实体",
    "设备导入过滤会清理既有实体",
    "设备导入过滤会迁移既有实体",
    "设备导入过滤会清理设备注册表",
    "设备 picker 必须加载设备列表才能继续",
    "设备 picker 仅配置期可用",
    "设备 picker 只能配置期使用",
    "options 不能调整设备选择",
    "options 无法重新打开设备 picker",
    "必须加载设备列表才能继续配置",
    "设备列表加载失败会阻止配置",
    "设备列表加载失败无法继续创建 entry",
    "设备列表加载失败无法继续配置",
    "HACS 发布完成",
    "HACS publication complete",
    "已通过 HACS 网站提交",
    "published to HACS",
    "集成已准备好发布到 HACS",
    "ready for HACS publication",
    "准备发布 ✅",
    "本地 HA 实测未完成",
    "本地 Home Assistant 实测未完成",
    "本地 Home Assistant 实测闭环",
    "补足本地 Home Assistant 实测闭环",
    "local HA validation is incomplete",
    "local Home Assistant validation is incomplete",
    "cp -R custom_components/yeelight_pro",
    "cp -r custom_components/yeelight_pro",
}
STALE_DOC_PATTERNS = {
    r"15\s+platforms",
    r"15\s*个",
    r"15\s*平台",
    r"85\s+passed",
    r"85\s+tests?",
    r"85\s*个测试",
    r"128\s+passed",
    r"128\s+tests?",
    r"128\s*个测试",
    r"189\s+passed",
    r"189\s+tests?",
    r"189\s*个测试",
    r"196\s+passed",
    r"196\s+tests?",
    r"196\s*个测试",
    r"198\s+passed",
    r"198\s+tests?",
    r"198\s*个测试",
    r"200\s+passed",
    r"200\s+tests?",
    r"200\s*个测试",
    r"204\s+passed",
    r"204\s+tests?",
    r"204\s*个测试",
    r"207\s+passed",
    r"207\s+tests?",
    r"207\s*个测试",
    r"210\s+passed",
    r"210\s+tests?",
    r"210\s*个测试",
    r"217\s+passed",
    r"217\s+tests?",
    r"217\s*个测试",
    r"219\s+passed",
    r"219\s+tests?",
    r"219\s*个测试",
    r"221\s+passed",
    r"221\s+tests?",
    r"221\s*个测试",
    r"225\s+passed",
    r"225\s+tests?",
    r"225\s*个测试",
    r"229\s+passed",
    r"229\s+tests?",
    r"229\s*个测试",
    r"232\s+passed",
    r"232\s+tests?",
    r"232\s*个测试",
    r"\d+\s+passed",
    r"\d+\s+tests?",
    r"(?:通过|共)\s*\d+\s*个测试",
    r"\d+\s*个测试",
    r"61\s+files",
    r"62\s+files",
    r"64\s+files",
    r"65\s+files",
    r"\d+\s+files",
    r"56\s*%",
    r"57\s*%",
    r"62\s*%",
    r"63\s*%",
    r"64\s*%",
    r"\d+\s*%",
    r"SSE\s*已",
    r"SSE\s+(?:is|support is)\s+implemented",
    r"\bSSE\b.{0,30}(?:runtime|transport|subscription|event notifications?|live updates?|push)",
    r"(?:runtime|transport|subscription|event notifications?|live updates?|push).{0,30}\bSSE\b",
    r"SSE.{0,20}(?:推送|事件通知|实时更新).{0,12}(?:已|支持|实现|启用|可用)",
    r"EventSource",
    r"Server-Sent\s+Events?",
    r"WebSocket\s*/\s*SSE",
    r"WebSocket\s*(?:or|and|\+)\s*SSE",
    r"WebSocket\s*(?:或|和|加)\s*SSE",
    r"WebSocket\s*/\s*SSE\s*/\s*subscription\s*尚未作为运行时能力完成",
    r"实时更新.*已",
    r"OAuth.*已(?:支持|实现|启用|可用)",
    r"OAuth\s+(?:is|support is)\s+implemented",
    r"Home Assistant OAuth.{0,24}(?:是否仍|取舍|product approval)",
    r"Decide whether Home Assistant OAuth should still be a first-party release goal",
    r"OAuth runtime task:\s*wire the existing no-network OAuth contract into Home Assistant config flow",
    r"本地网关.{0,20}已(?:支持|实现|启用|可用)",
    r"local gateway(?: support)? is implemented",
    r"mDNS\s+discovery\s+is\s+implemented",
    r"automatic\s+local\s+gateway\s+discovery\s+is\s+implemented",
    r"local\s+gateway\s+discovery\s+is\s+enabled\s+by\s+default",
    r"本地网关\s*mDNS\s*已实现",
    r"自动本地网关发现已实现",
    r"本地网关发现默认启用",
    r"live WebSocket\s+(?:is|updates are)\s+implemented",
    r"本地网关.{0,20}已(?:支持|实现|启用|可用)",
    r"家庭转移.*已(?:支持|实现|启用|可用)",
    r"house transfer\s+(?:is|support is)\s+implemented",
    r"device import filter.{0,40}(?:will|automatically|supports?|implemented).{0,20}"
    r"(?:delete|remove|hide|clean(?:s| up)?|migrate).{0,40}existing entit",
    r"device import filter.{0,40}(?:will|automatically|supports?|implemented).{0,20}"
    r"clean(?:s| up)?.{0,40}device registry",
    r"设备导入过滤.{0,20}(?:会|将|自动|已(?:支持|实现)|支持).{0,8}"
    r"(?:删除|禁用|隐藏|清理|迁移).{0,20}(?:既有|现有).*实体",
    r"设备导入过滤.{0,20}(?:会|将|自动|已(?:支持|实现)|支持).{0,8}"
    r"清理.{0,20}设备注册表",
    r"device picker.{0,40}(?:requires?|must load).{0,30}device list",
    r"device picker.{0,40}blocks?.{0,30}(?:setup|config(?:uration)?).{0,30}"
    r"(?:device list|loading devices?)",
    r"device list.{0,30}(?:load(?:ing)? failure|fails?).{0,30}blocks?.{0,30}"
    r"(?:setup|config(?:uration)?)",
    r"device picker.{0,30}(?:setup-only|only works during setup)",
    r"device picker.{0,40}cannot be (?:changed|edited|reopened).{0,20}options",
    r"options.{0,30}cannot.{0,30}(?:change|edit|reopen).{0,30}"
    r"(?:selected devices?|device picker)",
    r"设备\s*picker.{0,20}必须.{0,20}加载.{0,10}设备列表.{0,20}"
    r"(?:继续|配置|创建)",
    r"设备\s*picker.{0,20}(?:仅|只).{0,8}配置期.{0,8}(?:可用|使用)",
    r"options.{0,20}(?:不能|无法).{0,20}(?:调整|修改|重新打开).{0,20}"
    r"(?:设备选择|设备\s*picker)",
    r"设备列表.{0,12}加载失败.{0,20}(?:阻止|无法|不能).{0,20}"
    r"(?:配置|继续|创建)",
    r"本地\s*(?:HA|Home Assistant)\s*实测.{0,12}(?:未完成|进行中|待完成|待补足)",
    r"补足本地\s*(?:HA|Home Assistant)\s*实测闭环",
    r"local\s+(?:HA|Home Assistant)\s+validation\s+is\s+incomplete",
    r"cp\s+-[Rr]\s+custom_components/yeelight_pro",
}
