"""Required release file registry for Yeelight Pro preflight checks."""

from __future__ import annotations

from scripts.hacs_preflight_release_file_groups import (
    RELEASE_COMPONENT_FILES,
    RELEASE_TEST_FILES,
)

_RELEASE_ROOT_FILES = {
    "CHANGELOG.md",
    "CONTRIBUTING.md",
    "README.md",
    "README_zh.md",
    "RELEASE_GUIDE.md",
    "docs/AUTOMATION_EXAMPLES.md",
    "docs/CORE_MIGRATION_STRATEGY.md",
    "docs/GOAL_COMPLETION_AUDIT.md",
    "docs/IOT_SPEC_REGISTRY.md",
    "docs/LOCAL_CONTROL.md",
    "docs/QUALITY_SCALE_GOLD_GAP_ANALYSIS.md",
    "docs/SUPPORTED_DEVICES.md",
    "docs/TROUBLESHOOTING.md",
    "docs/WORKS_WITH_HOME_ASSISTANT_APPLICATION_GUIDE.md",
    "docs/WORKS_WITH_HOME_ASSISTANT_HANDOVER.md",
    "hacs.json",
    "manual_ha_test_checks.py",
    "manual_ha_test_config_checks.py",
    "manual_ha_test_core_checks.py",
    "manual_ha_test_helpers.py",
    "manual_ha_test_projector_checks.py",
    "test_actual_environment.py",
    "test_complete_ha.py",
    "test_functional.py",
    "test_real_ha_environment.py",
}

_RELEASE_SCRIPT_FILES = {
    "scripts/__init__.py",
    "scripts/check_release_zip.py",
    "scripts/hacs_preflight.py",
    "scripts/hacs_preflight_claims.py",
    "scripts/hacs_preflight_contracts.py",
    "scripts/hacs_preflight_core.py",
    "scripts/export_private_house_control_report.py",
    "scripts/export_private_house_coverage_matrix.py",
    "scripts/hacs_preflight_data.py",
    "scripts/hacs_preflight_diagnostics.py",
    "scripts/hacs_preflight_diagnostics_data.py",
    "scripts/hacs_preflight_entity_filter_data.py",
    "scripts/hacs_preflight_entity_filters.py",
    "scripts/hacs_preflight_iot_registry_data.py",
    "scripts/hacs_preflight_iot_registry_projection_data.py",
    "scripts/hacs_preflight_legacy_entrypoints.py",
    "scripts/hacs_preflight_lifecycle.py",
    "scripts/hacs_preflight_local_ha.py",
    "scripts/hacs_preflight_local_ha_probes.py",
    "scripts/hacs_preflight_local_ha_protocol_contracts.py",
    "scripts/hacs_preflight_local_ha_release.py",
    "scripts/hacs_preflight_local_ha_runtime.py",
    "scripts/hacs_preflight_local_ha_runtime_capability_sources.py",
    "scripts/hacs_preflight_local_ha_runtime_core_tests.py",
    "scripts/hacs_preflight_local_ha_runtime_source_tokens.py",
    "scripts/hacs_preflight_local_ha_runtime_sources.py",
    "scripts/hacs_preflight_local_ha_runtime_tests.py",
    "scripts/hacs_preflight_local_ha_runtime_verifier_sources.py",
    "scripts/hacs_preflight_local_ha_runtime_verifier_storage.py",
    "scripts/hacs_preflight_local_ha_runtime_verifier_tests.py",
    "scripts/hacs_preflight_local_ha_split_contracts.py",
    "scripts/hacs_preflight_manual_tests.py",
    "scripts/hacs_preflight_platform_mapping_data.py",
    "scripts/hacs_preflight_projector_data.py",
    "scripts/hacs_preflight_push_contracts.py",
    "scripts/hacs_preflight_release_file_groups.py",
    "scripts/hacs_preflight_release_files.py",
    "scripts/hacs_preflight_release_test_files.py",
    "scripts/hacs_preflight_runtime_options.py",
    "scripts/hacs_preflight_scan_login_contracts.py",
    "scripts/hacs_preflight_split_client_contracts.py",
    "scripts/hacs_preflight_split_contracts.py",
    "scripts/local_ha_verification/cli.py",
    "scripts/local_ha_verification/constants.py",
    "scripts/local_ha_verification/diagnostics.py",
    "scripts/local_ha_verification/diagnostics_websocket.py",
    "scripts/local_ha_verification/flow_contracts.py",
    "scripts/local_ha_verification/i18n.py",
    "scripts/local_ha_verification/i18n_payloads.py",
    "scripts/local_ha_verification/i18n_source.py",
    "scripts/local_ha_verification/install.py",
    "scripts/local_ha_verification/options.py",
    "scripts/local_ha_verification/platforms.py",
    "scripts/local_ha_verification/report.py",
    "scripts/local_ha_verification/runtime.py",
    "scripts/local_ha_verification/runtime_entities.py",
    "scripts/local_ha_verification/service_schema.py",
    "scripts/local_ha_verification/service_schema_runtime.py",
    "scripts/local_ha_verification/services.py",
    "scripts/local_ha_verification/storage.py",
    "scripts/local_ha_verification/storage_device_quality.py",
    "scripts/local_ha_verification/storage_entity_quality.py",
    "scripts/local_ha_verification/storage_entries.py",
    "scripts/local_ha_verification/storage_helpers.py",
    "scripts/preflight_ast.py",
    "scripts/private_house_audit/__init__.py",
    "scripts/private_house_audit/classification.py",
    "scripts/private_house_audit/classification_rows.py",
    "scripts/private_house_audit/control_coverage.py",
    "scripts/private_house_audit/coverage_matrix_rows.py",
    "scripts/private_house_audit/coverage_model.py",
    "scripts/private_house_audit/inventory.py",
    "scripts/private_house_audit/io_helpers.py",
    "scripts/private_house_audit/projection.py",
    "scripts/private_house_audit/report.py",
    "scripts/private_push_probe/__init__.py",
    "scripts/private_push_probe/cli.py",
    "scripts/private_push_probe/io_helpers.py",
    "scripts/private_push_probe/matching.py",
    "scripts/private_push_probe/models.py",
    "scripts/private_push_probe/push_probe.py",
    "scripts/private_push_probe/snapshot.py",
    "scripts/private_push_probe/topology.py",
    "scripts/probe_private_push_control_echo.py",
    "scripts/probe_private_push_broadcast.py",
    "scripts/probe_private_push_topology.py",
    "scripts/summarize_private_house_coverage.py",
    "scripts/sync_local_ha_runtime.py",
    "scripts/verify_cloud_devices.py",
    "scripts/verify_lan_gateway.py",
    "scripts/verify_local_ha.py",
    "scripts/verify_local_ha_recovery.py",
    "scripts/verify_local_ha_soak.py",
    "scripts/verify_probe_client.py",
    "scripts/verify_push_websocket.py",
    "scripts/verify_scan_login.py",
}

REQUIRED_RELEASE_FILES = (
    _RELEASE_ROOT_FILES
    | _RELEASE_SCRIPT_FILES
    | RELEASE_COMPONENT_FILES
    | RELEASE_TEST_FILES
)
